/**
 * Batch 3 of CBLE Questions
 * 40 new questions
 */

export const batch3Questions = [
    // ============================================
    // DOMAIN 1: Classification (HTSUS / GRIs)
    // ============================================
    {
        stem: 'Under GRI 3(b), which of the following is the key factor in determining the "essential character" of a set or composite good?',
        option_a: 'The order in which the headings appear',
        option_b: 'The nature of the material, its bulk, quantity, weight, value, or the role of a constituent material in relation to the use of the goods',
        option_c: 'The country of origin of the most expensive component',
        option_d: 'The HTSUS Chapter which contains the majority of the components',
        option_e: 'The intended use of the ultimate consumer',
        correct_answer: 'B',
        rationale: 'Explanatory Note VIII to GRI 3(b) states that essential character may be determined by the nature of the material, its bulk, quantity, weight, value, or the role of a constituent material.',
        reference_cue: 'GRI 3(b)',
        difficulty: 4,
        domain_index: 1,
    },
    {
        stem: 'Which HTSUS Chapter covers "Footwear, gaiters and the like; parts of such articles"?',
        option_a: 'Chapter 61',
        option_b: 'Chapter 62',
        option_c: 'Chapter 63',
        option_d: 'Chapter 64',
        option_e: 'Chapter 65',
        correct_answer: 'D',
        rationale: 'Chapter 64 specifically covers footwear and parts thereof.',
        reference_cue: 'HTSUS Chapter 64',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Articles of jewelry made of base metal clad with precious metal are classified in:',
        option_a: 'Chapter 71',
        option_b: 'Chapter 72',
        option_c: 'Chapter 73',
        option_d: 'Chapter 83',
        option_e: 'Chapter 98',
        correct_answer: 'A',
        rationale: 'Chapter 71 covers pearls, precious stones, precious metals, and articles thereof, including imitation jewelry.',
        reference_cue: 'HTSUS Chapter 71',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'In HTSUS Section XI (Textiles), the term "man-made fibers" includes:',
        option_a: 'Silk only',
        option_b: 'Cotton and linen',
        option_c: 'Synthetic and artificial fibers',
        option_d: 'Wool and fine animal hair',
        option_e: 'Paper yarn',
        correct_answer: 'C',
        rationale: 'Section XI Note 1 defines man-made fibers as synthetic or artificial filaments or staple fibers.',
        reference_cue: 'Section XI Note 1',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'Under GRI 5(b), packing materials and packing containers are classified with the goods they contain if they are:',
        option_a: 'Valued at 10% or more of the goods',
        option_b: 'Of a kind normally used for packing such goods',
        option_c: 'Specifically designed for long-term use',
        option_d: 'Made of a different material than the goods',
        option_e: 'Heavier than 5 kilograms',
        correct_answer: 'B',
        rationale: 'GRI 5(b) states that packing materials/containers are classified with the goods if they are of a kind normally used for packing such goods, unless suitable for repetitive use.',
        reference_cue: 'GRI 5(b)',
        difficulty: 3,
        domain_index: 1,
    },

    // ============================================
    // DOMAIN 4: Broker Duties / POA / Records / Bonds
    // ============================================
    {
        stem: 'A broker must retain powers of attorney for how long after the date of their revocation or the date the broker last representative action was taken?',
        option_a: '1 year',
        option_b: '3 years',
        option_c: '5 years',
        option_d: '10 years',
        option_e: 'Indefinitely',
        correct_answer: 'C',
        rationale: '19 CFR 141.68(c) and 19 CFR 111.23(a) require records, including POAs, to be kept for 5 years.',
        reference_cue: '19 CFR 111.23',
        difficulty: 3,
        domain_index: 4,
    },
    {
        stem: 'What is the maximum monetary penalty that CBP may impose on a broker for each violation of 19 CFR 111?',
        option_a: '$1,000',
        option_b: '$5,000',
        option_c: '$10,000',
        option_d: '$30,000',
        option_e: '$100,000',
        correct_answer: 'D',
        rationale: 'Under 19 CFR 111.91, CBP may assess a monetary penalty against a broker in an amount not to exceed $30,000.',
        reference_cue: '19 CFR 111.91',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'If a broker\'s license is suspended, for how long can it be suspended?',
        option_a: 'Maximum 30 days',
        option_b: 'Maximum 1 year',
        option_c: 'Minimum 5 years',
        option_d: 'For a specific period or until certain conditions are met',
        option_e: 'Indefinitely always',
        correct_answer: 'D',
        rationale: '111.53 provides for suspension for a specific timeframe or until specific conditions (like retraining or audit) are completed.',
        reference_cue: '19 CFR 111.53',
        difficulty: 4,
        domain_index: 4,
    },

    // ============================================
    // DOMAIN 0: Entry / Entry Summary / Release
    // ============================================
    {
        stem: 'What is the "time of entry" for merchandise arriving by vessel that is not released under an immediate delivery permit?',
        option_a: 'When the vessel enters the port limits',
        option_b: 'When the entry is filed in proper form with estimated duties deposited',
        option_c: 'When the master of the vessel signs the manifest',
        option_d: '48 hours after arrival',
        option_e: 'When the cargo is unloaded onto the pier',
        correct_answer: 'B',
        rationale: '19 CFR 141.68(a) states the time of entry is when the entry is filed in proper form and estimated duties are deposited.',
        reference_cue: '19 CFR 141.68(a)',
        difficulty: 4,
        domain_index: 0,
    },
    {
        stem: 'Merchandise remaining in a Customs bonded warehouse for more than 5 years is considered:',
        option_a: 'Abandoned to the government',
        option_b: 'Exempt from duty',
        option_c: 'Subject to a 50% surcharge',
        option_d: 'Property of the warehouse proprietor',
        option_e: 'Eligible for a 2-year extension',
        correct_answer: 'A',
        rationale: '19 CFR 144.5 marks merchandise as abandoned if it stays beyond the 5-year limit without being entered for consumption or exported.',
        reference_cue: '19 CFR 144.5',
        difficulty: 3,
        domain_index: 0,
    },

    // ============================================
    // DOMAIN 2: Valuation (19 CFR 152)
    // ============================================
    {
        stem: 'Deductive value is based on the price at which the imported merchandise is sold in the U.S. in its condition as imported at or about the date of importation to:',
        option_a: 'Related parties',
        option_b: 'Unrelated persons',
        option_c: 'The highest bidder',
        option_d: 'Non-profit organizations',
        option_e: 'Customs brokers',
        correct_answer: 'B',
        rationale: '19 CFR 152.105 states deductive value must be based on sales to persons who are not related to the seller.',
        reference_cue: '19 CFR 152.105',
        difficulty: 4,
        domain_index: 2,
    },
    {
        stem: 'In Computed Value, "General Expenses" includes:',
        option_a: 'Direct manufacturing costs only',
        option_b: 'Direct and indirect costs of marketing the goods',
        option_c: 'Costs of raw materials',
        option_d: 'Taxes paid in the U.S.',
        option_e: 'Broker fees',
        correct_answer: 'B',
        rationale: 'General expenses in computed value cover the overhead and marketing costs incurred by the manufacturer.',
        reference_cue: '19 CFR 152.106',
        difficulty: 4,
        domain_index: 2,
    },

    // ============================================
    // DOMAIN 3: Trade Programs / Origin
    // ============================================
    {
        stem: 'Under USMCA, the term "Originating" means a good that:',
        option_a: 'Was shipped from a USMCA country',
        option_b: 'Meets the rules of origin set forth in General Note 11',
        option_c: 'Has a "Made in North America" label',
        option_d: 'Was manufactured by a North American company',
        option_e: 'Contains at least 10% North American components',
        correct_answer: 'B',
        rationale: 'General Note 11 to the HTSUS contains the specific USMCA rules of origin.',
        reference_cue: 'HTSUS General Note 11',
        difficulty: 3,
        domain_index: 3,
    },
    {
        stem: 'What is the "wholly obtained" criterion for origin?',
        option_a: 'The good contains no foreign materials',
        option_b: 'The good was assembled in a warehouse',
        option_c: 'The good has a 50% RVC',
        option_d: 'The shipping container is from the same country',
        option_e: 'The brand is headquartered in the country of origin',
        correct_answer: 'A',
        rationale: 'A good is wholly obtained if it is produced entirely in a country from materials originating there (e.g., minerals extracted, crops harvested).',
        reference_cue: '19 CFR 102.1',
        difficulty: 2,
        domain_index: 3,
    },

    // Domain 1 again - Chapter specifics
    {
        stem: 'Articles of apparel and clothing accessories, knitted or crocheted, are classified in:',
        option_a: 'Chapter 60',
        option_b: 'Chapter 61',
        option_c: 'Chapter 62',
        option_d: 'Chapter 63',
        option_e: 'Chapter 54',
        correct_answer: 'B',
        rationale: 'Chapter 61 covers knitted/crocheted apparel. Chapter 62 covers woven apparel.',
        reference_cue: 'HTSUS Chapter 61',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'The GRI that allows for classification by "Essential Character" is:',
        option_a: 'GRI 1',
        option_b: 'GRI 2',
        option_c: 'GRI 3(b)',
        option_d: 'GRI 3(c)',
        option_e: 'GRI 6',
        correct_answer: 'C',
        rationale: 'GRI 3(b) is the rule used for mixtures, composite goods, and sets based on essential character.',
        reference_cue: 'GRI 3(b)',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'According to the HTSUS, the "General Notes" are located:',
        option_a: 'At the end of each chapter',
        option_b: 'At the very beginning of the tariff schedule',
        option_c: 'In a separate manual issued by the ITC',
        option_d: 'Inside the Index only',
        option_e: 'Only in the electronic version',
        correct_answer: 'B',
        rationale: 'General Notes provide overarching rules for duty rates and trade programs and are found at the beginning of the HTSUS.',
        reference_cue: 'HTSUS Structure',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Under GRI 6, classification at the subheading level is determined according to:',
        option_a: 'The same rules as the heading level, but comparing only subheadings at the same level',
        option_b: 'The weight of the article only',
        option_c: 'The price of the article',
        option_d: 'A separate set of rules called the Subheading Rules (SRI)',
        option_e: 'The alphabet',
        correct_answer: 'A',
        rationale: 'GRI 6 states that classification in the subheadings of a heading shall be determined according to the terms of those subheadings and any related subheading notes.',
        reference_cue: 'GRI 6',
        difficulty: 4,
        domain_index: 1,
    },
    {
        stem: 'Chapter 73 of the HTSUS covers articles of:',
        option_a: 'Copper',
        option_b: 'Aluminum',
        option_c: 'Iron or Steel',
        option_d: 'Lead',
        option_e: 'Zinc',
        correct_answer: 'C',
        rationale: 'Chapter 73 is dedicated to articles of iron or steel.',
        reference_cue: 'HTSUS Chapter 73',
        difficulty: 2,
        domain_index: 1,
    },

    // Domain 4 again
    {
        stem: 'A broker must provide a client with a written statement of the broker fees and charges:',
        option_a: 'Daily',
        option_b: 'Upon Request',
        option_c: 'Only if the fee exceeds $10,000',
        option_d: 'Before every entry is filed',
        option_e: 'Within 90 days of the end of the year',
        correct_answer: 'B',
        rationale: '111.36(c) requires brokers to provide accounting of fees when requested by the client.',
        reference_cue: '19 CFR 111.36',
        difficulty: 3,
        domain_index: 4,
    },
    {
        stem: 'Any licensed customs broker who has been convicted of a felony must notify CBP within:',
        option_a: '24 hours',
        option_b: '5 days',
        option_c: '30 days',
        option_d: '6 months',
        option_e: 'The next triennial report filing',
        correct_answer: 'C',
        rationale: 'Brokers must report felony convictions or certain other legal changes within 30 days under 111.30.',
        reference_cue: '19 CFR 111.30',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'Who can revoke a customs broker license?',
        option_a: 'The Secretary of Homeland Security',
        option_b: 'The Commissioner of CBP',
        option_c: 'The Secretary of the Treasury',
        option_d: 'The Port Director',
        option_e: 'Only a Federal Judge',
        correct_answer: 'C',
        rationale: 'While CBP administers the program, the Secretary of the Treasury (or their delegate) has the legal authority to revoke or suspend licenses.',
        reference_cue: '19 CFR 111.53',
        difficulty: 5,
        domain_index: 4,
    },

    // Domain 5: Marking
    {
        stem: 'The statutory authority for country of origin marking is:',
        option_a: '19 USC 1304',
        option_b: '19 USC 1484',
        option_c: '19 USC 1592',
        option_d: '19 USC 1514',
        option_e: '19 USC 1625',
        correct_answer: 'A',
        rationale: '19 USC 1304 is the primary statute requiring every article of foreign origin to be marked in a conspicuous place.',
        reference_cue: '19 USC 1304',
        difficulty: 3,
        domain_index: 5,
    },
    {
        stem: 'For marking purposes, a "Combining" operation is usually considered to result in:',
        option_a: 'A substantial transformation',
        option_b: 'No change in country of origin',
        option_c: 'A mandatory duty of 10%',
        option_d: 'A new HTSUS chapter',
        option_e: 'An exemption for the ultimate purchaser',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 134 rules, simple combining or packaging of components usually does NOT result in a substantial transformation.',
        reference_cue: '19 CFR 134.1',
        difficulty: 4,
        domain_index: 5,
    },

    // Domain 6: Protest
    {
        stem: 'How many days does CBP have to decide on a protest after it has been filed?',
        option_a: '30 days',
        option_b: '180 days',
        option_c: '2 years',
        option_d: '314 days',
        option_e: 'There is no statutory deadline for standard protests',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 174.21, CBP shall review and act on a protest within 2 years from the date it was filed.',
        reference_cue: '19 CFR 174.21',
        difficulty: 4,
        domain_index: 6,
    },
    {
        stem: 'If a protest is not filed within 180 days of liquidation, the liquidation becomes:',
        option_a: 'Void',
        option_b: 'Final and conclusive upon all persons',
        option_c: 'Subject to a second 180-day window',
        option_d: 'Automatically reliquidated at the lower rate',
        option_e: 'Suspended',
        correct_answer: 'B',
        rationale: '19 USC 1514 states that decisions become final and conclusive if not protested within the 180-day period.',
        reference_cue: '19 USC 1514',
        difficulty: 3,
        domain_index: 6,
    },

    // Domain 7: Other
    {
        stem: 'Which agency regulates the importation of wireless devices and radio frequency emitters?',
        option_a: 'EPA',
        option_b: 'FCC',
        option_c: 'CPSC',
        option_d: 'FDA',
        option_e: 'DOE',
        correct_answer: 'B',
        rationale: 'The Federal Communications Commission (FCC) regulates RF devices.',
        reference_cue: '19 CFR 12.90',
        difficulty: 2,
        domain_index: 7,
    },
    {
        stem: 'What is the standard amount of time for a "General Order" (G.O.) notification?',
        option_a: '5 working days after arrival',
        option_b: '15 working days after arrival',
        option_c: '30 calendar days after arrival',
        option_d: '15 calendar days after arrival',
        option_e: '90 days after arrival',
        correct_answer: 'D',
        rationale: 'Merchandise not entered or moved in-bond within 15 calendar days of arrival is sent to a General Order warehouse.',
        reference_cue: '19 CFR 127.1',
        difficulty: 3,
        domain_index: 7,
    },

    // Domain 0: Entry again
    {
        stem: 'The importer of record must provide a "Reconciliation" entry to CBP within how many months for value issues?',
        option_a: '12 months',
        option_b: '15 months',
        option_c: '21 months',
        option_d: '5 years',
        option_e: 'Valid until liquidation',
        correct_answer: 'C',
        rationale: 'Reconciliation entries for value (and others except NAFTA) must be filed within 21 months of the earliest entry date.',
        reference_cue: 'CBP Reconciliation Guide',
        difficulty: 5,
        domain_index: 0,
    },
    {
        stem: 'A consumption entry summary for a shipment subject to Antidumping duty must be filed:',
        option_a: 'Within 10 working days of release',
        option_b: 'As a "Live Entry" (entry and summary together)',
        option_c: 'Within 30 days of release',
        option_d: 'Only by a national broker',
        option_e: 'Within 1 year',
        correct_answer: 'B',
        rationale: 'CBP often requires AD/CVD entries to be filed as live entries to ensure duty deposit prior to release.',
        reference_cue: '19 CFR 141.0a',
        difficulty: 4,
        domain_index: 0,
    },

    // Domain 1: Class again
    {
        stem: 'Heading 8471 refers to automatic data processing machines. A keyboard or a mouse imported with a laptop as a set would be classified under:',
        option_a: 'Heading 8473 (Parts)',
        option_b: 'Heading 8471 (Input/Output units)',
        option_c: 'Heading 8518 (Microphones)',
        option_d: 'The material they are made of (Plastic Heading 3926)',
        option_e: 'GRI 5 Case classification',
        correct_answer: 'B',
        rationale: 'Keyboards and mice are specifically listed as input units in the notes to 8471.',
        reference_cue: 'HTSUS 8471',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'Section XVI covers machinery and electrical equipment. Which of the following is NOT covered in Section XVI?',
        option_a: 'Nuclear reactors',
        option_b: 'Electric motors',
        option_c: 'Vehicles and trailers',
        option_d: 'Steam boilers',
        option_e: 'Pumps for liquids',
        correct_answer: 'C',
        rationale: 'Vehicles are covered in Section XVII. Machinery is in Section XVI.',
        reference_cue: 'HTSUS Section XVI',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Chapter 29 of the HTSUS covers:',
        option_a: 'Inorganic chemicals',
        option_b: 'Organic chemicals',
        option_c: 'Pharmaceutical products',
        option_d: 'Fertilizers',
        option_e: 'Essential oils',
        correct_answer: 'B',
        rationale: 'Chapter 28 is inorganic; Chapter 29 is organic chemicals.',
        reference_cue: 'HTSUS Chapter 29',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'Which HTSUS Chapter would you use for "Natural or cultured pearls, precious or semi-precious stones"?',
        option_a: '71',
        option_b: '72',
        option_c: '73',
        option_d: '70',
        option_e: '68',
        correct_answer: 'A',
        rationale: 'Chapter 71 is the home for pearls and precious stones.',
        reference_cue: 'HTSUS Chapter 71',
        difficulty: 1,
        domain_index: 1,
    },
    {
        stem: 'A "Functional Unit" is classified under the heading appropriate to that function if the components are:',
        option_a: 'Imported in the same container',
        option_b: 'Intended to contribute together to a clearly defined function',
        option_c: 'All from the same manufacturer',
        option_d: 'Used by the same person',
        option_e: 'Under the same bill of lading',
        correct_answer: 'B',
        rationale: 'Section XVI Note 4 defines functional units as components intended to contribute together to a defined function.',
        reference_cue: 'Section XVI Note 4',
        difficulty: 5,
        domain_index: 1,
    },

    // Domain 4: Broker
    {
        stem: 'If a broker\'s employee is arrested for a crime involving customs business, the broker must notify CBP within:',
        option_a: '10 days',
        option_b: '30 days',
        option_c: 'Immediately',
        option_d: 'The end of the week',
        option_e: 'Wait for a conviction',
        correct_answer: 'B',
        rationale: 'Under 111.28, brokers must report certain employee background changes including arrests or convictions within 30 days.',
        reference_cue: '19 CFR 111.28',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'The triennial report for brokers is due on the first of February of:',
        option_a: 'Every year',
        option_b: 'Every other year',
        option_c: 'Every third year',
        option_d: 'Every fifth year',
        option_e: 'Leap years only',
        correct_answer: 'C',
        rationale: 'Triennial means every three years.',
        reference_cue: '19 CFR 111.30',
        difficulty: 1,
        domain_index: 4,
    },
    {
        stem: 'A broker can use the name of an unlicensed person in their firm name ONLY if:',
        option_a: 'The unlicensed person is the majority owner',
        option_b: 'CBP grants a special waiver',
        option_c: 'The unlicensed person has a clean record',
        option_d: 'It is a partnership and the unlicensed person is a partner',
        option_e: 'This is never permitted',
        correct_answer: 'D',
        rationale: 'Partnerships can include unlicensed partners in the firm name under certain conditions in 111.30.',
        reference_cue: '19 CFR 111.30',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'Under what circumstances can a broker accept compensation from a third party for customs business without client consent?',
        option_a: 'If the client is over 65',
        option_b: 'If the fee is under $50',
        option_c: 'Never',
        option_d: 'If the third party is the carrier',
        option_e: 'If the third party is a bank',
        correct_answer: 'C',
        rationale: '111.39/36 requires full disclosure and client consent for any third-party compensation related to the client\'s business.',
        reference_cue: '19 CFR 111.36',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'Can a broker provide a discount to an importer if the importer agrees to use the broker for 5 years?',
        option_a: 'Yes, this is competitive pricing',
        option_b: 'No, this is "buying business"',
        option_c: 'Only if the discount is less than 10%',
        option_d: 'Yes, but it must be reported to the Secretary of the Treasury',
        option_e: 'Only for agricultural shipments',
        correct_answer: 'A',
        rationale: 'While brokers have professional duties, they are permitted to set their own pricing/discounts in a competitive market.',
        reference_cue: '19 CFR 111',
        difficulty: 3,
        domain_index: 4,
    },
];
