/**
 * Batch 6: Valuation & Trade Programs
 * 80 questions
 */
export const batch6Questions = [
    // DOMAIN 2: Valuation (40 questions)
    {
        stem: 'Transaction value is defined as the price actually paid or payable for merchandise when sold for exportation to the US, plus certain statutory additions. Which is NOT a statutory addition?',
        option_a: 'Packing costs incurred by the buyer',
        option_b: 'Selling commission paid by the buyer',
        option_c: 'Royalties related to the imported merchandise',
        option_d: 'Buying commission paid by the buyer',
        option_e: 'The value of assists',
        correct_answer: 'D',
        rationale: 'Buying commissions are NOT added to transaction value. Selling commissions, assists, royalties, and packing costs are statutory additions.',
        reference_cue: '19 CFR 152.103(b)',
        difficulty: 2,
        domain_index: 2
    },
    {
        stem: 'Under 19 CFR 152.103, which of the following is considered an "assist"?',
        option_a: 'Import duty paid by the buyer',
        option_b: 'Materials supplied by the buyer free of charge for use in production',
        option_c: 'Insurance costs for domestic transport',
        option_d: 'Buying commission',
        option_e: 'Freight charges within the US',
        correct_answer: 'B',
        rationale: 'An assist includes materials, components, tools, dies, molds, and engineering/development work supplied by the buyer for use in producing the imported merchandise.',
        reference_cue: '19 CFR 152.102(a)',
        difficulty: 2,
        domain_index: 2
    },
    {
        stem: 'The hierarchy of valuation methods after transaction value is:',
        option_a: 'Deductive → Computed → Identical → Similar',
        option_b: 'Identical → Similar → Deductive → Computed',
        option_c: 'Similar → Identical → Computed → Deductive',
        option_d: 'Computed → Deductive → Identical → Similar',
        option_e: 'Identical → Similar → Computed → Deductive',
        correct_answer: 'B',
        rationale: 'The statutory hierarchy is: Transaction Value → Transaction Value of Identical → Transaction Value of Similar → Deductive → Computed → Fallback.',
        reference_cue: '19 CFR 152.101',
        difficulty: 2,
        domain_index: 2
    },
    {
        stem: 'For valuation purposes, "identical merchandise" must be:',
        option_a: 'Produced in the same country and by the same manufacturer',
        option_b: 'The same in all respects, produced in the same country',
        option_c: 'Of the same class or kind and commercially interchangeable',
        option_d: 'Made from the same materials',
        option_e: 'Sold at the same price',
        correct_answer: 'B',
        rationale: 'Identical merchandise is merchandise that is the same in all respects, including physical characteristics, quality, and reputation, produced in the same country.',
        reference_cue: '19 CFR 152.102(e)',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: '"Similar merchandise" for valuation purposes must:',
        option_a: 'Be identical in every respect',
        option_b: 'Have closely resembling characteristics and be commercially interchangeable',
        option_c: 'Be from the same manufacturer',
        option_d: 'Have the same HTS classification',
        option_e: 'Be sold at the same time',
        correct_answer: 'B',
        rationale: 'Similar merchandise has closely resembling characteristics, is commercially interchangeable, and is produced in the same country.',
        reference_cue: '19 CFR 152.102(h)',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: 'Under deductive value, which of the following is deducted from the US selling price?',
        option_a: 'Foreign inland freight',
        option_b: 'Commissions or profit and general expenses in the US',
        option_c: 'Cost of materials used in production',
        option_d: 'Export packing costs',
        option_e: 'Buying agent commissions',
        correct_answer: 'B',
        rationale: 'Deductive value starts with the US selling price and deducts: commissions/profit, transportation/insurance in the US, customs duties, and further processing costs.',
        reference_cue: '19 CFR 152.105',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: 'Computed value is based on:',
        option_a: 'The US selling price minus deductions',
        option_b: 'The cost of materials, fabrication, profit, and general expenses in the country of production',
        option_c: 'The average price of identical merchandise',
        option_d: 'The replacement cost in the domestic market',
        option_e: 'CIF value at the port of export',
        correct_answer: 'B',
        rationale: 'Computed value equals the sum of materials, fabrication costs, profit, general expenses, and packing costs in the country of production.',
        reference_cue: '19 CFR 152.106',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: 'International freight and insurance charges to the US port of entry are:',
        option_a: 'Always included in dutiable value',
        option_b: 'Never included in dutiable value',
        option_c: 'Not included in transaction value under US law',
        option_d: 'Only included for air shipments',
        option_e: 'Only included for vessel shipments',
        correct_answer: 'C',
        rationale: 'Unlike CIF-based countries, the US uses FOB valuation. International freight and insurance are NOT included in transaction value.',
        reference_cue: '19 CFR 152.103(a)(5)',
        difficulty: 2,
        domain_index: 2
    },
    {
        stem: 'A royalty payment must be added to transaction value if:',
        option_a: 'It relates to any intellectual property',
        option_b: 'It relates to the imported merchandise and is a condition of sale',
        option_c: 'It exceeds 5% of the merchandise value',
        option_d: 'The buyer and seller are related',
        option_e: 'It is paid to a third party',
        correct_answer: 'B',
        rationale: 'Royalty/license fees are dutiable additions only if they relate to the imported merchandise AND their payment is a condition of sale.',
        reference_cue: '19 CFR 152.103(b)',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: 'When the buyer and seller are related, transaction value is acceptable if:',
        option_a: 'The relationship did not influence the price',
        option_b: 'The buyer is a wholly-owned subsidiary',
        option_c: 'Both parties are in the same country',
        option_d: 'The transaction is at arm\'s length under transfer pricing rules',
        option_e: 'CBP grants a waiver',
        correct_answer: 'A',
        rationale: 'Transaction value between related parties is acceptable if CBP determines the relationship did not influence the price paid.',
        reference_cue: '19 CFR 152.103(j)',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: 'The "fallback" method of valuation under 19 CFR 152.107 prohibits basing value on:',
        option_a: 'Reasonable adjustments to other methods',
        option_b: 'Domestic US selling prices of US-origin goods',
        option_c: 'Greater flexibility applied to prior methods',
        option_d: 'Price data from identical goods sold at different times',
        option_e: 'All of the above',
        correct_answer: 'B',
        rationale: 'The fallback method cannot be based on US domestic prices, arbitrary values, minimum values, or the highest of alternative values.',
        reference_cue: '19 CFR 152.107',
        difficulty: 4,
        domain_index: 2
    },
    {
        stem: 'Which of the following inland freight charges is included in transaction value?',
        option_a: 'Freight from the US port to the buyer\'s warehouse',
        option_b: 'Freight from the factory to the port of export',
        option_c: 'Both domestic and foreign inland freight',
        option_d: 'Neither domestic nor foreign inland freight',
        option_e: 'Only if the buyer pays the freight',
        correct_answer: 'B',
        rationale: 'Foreign inland freight (factory to port of export) is included in transaction value. US inland freight is not.',
        reference_cue: '19 CFR 152.103(a)(5)',
        difficulty: 3,
        domain_index: 2
    },
    {
        stem: 'An importer requests CBP to use computed value before deductive value. This is:',
        option_a: 'Never permitted',
        option_b: 'Permitted at the importer\'s request',
        option_c: 'Only permitted for related party transactions',
        option_d: 'Automatically applied when deductive value is unavailable',
        option_e: 'Permitted only with a court order',
        correct_answer: 'B',
        rationale: 'The importer may request reversal of the order of deductive and computed value, using computed before deductive.',
        reference_cue: '19 USC 1401a(a)(2)',
        difficulty: 4,
        domain_index: 2
    },
    {
        stem: 'Tools, dies, and molds provided by the buyer to the foreign manufacturer are:',
        option_a: 'Not relevant to valuation',
        option_b: 'Classified as assists and added to transaction value',
        option_c: 'Deducted from the price paid',
        option_d: 'Only relevant if domestically produced',
        option_e: 'Considered buying commissions',
        correct_answer: 'B',
        rationale: 'Tools, dies, molds, and similar items furnished by the buyer are assists. Their value must be apportioned and added to transaction value.',
        reference_cue: '19 CFR 152.102(a)',
        difficulty: 2,
        domain_index: 2
    },
    {
        stem: 'Engineering and development work performed in the US and provided to the foreign manufacturer:',
        option_a: 'Is always an assist that must be added',
        option_b: 'Is NOT an assist because it was performed in the US',
        option_c: 'Is only an assist if performed by the manufacturer',
        option_d: 'Reduces the transaction value',
        option_e: 'Is treated the same as a buying commission',
        correct_answer: 'B',
        rationale: 'Engineering, development, artwork, design work, and plans undertaken in the United States are specifically excluded from the definition of assists.',
        reference_cue: '19 CFR 152.102(a)(4)',
        difficulty: 4,
        domain_index: 2
    },
    // DOMAIN 3: Trade Programs / Origin (25 questions)
    {
        stem: 'Under USMCA, what is the minimum regional value content (RVC) using the transaction value method for most goods?',
        option_a: '35%',
        option_b: '50%',
        option_c: '60%',
        option_d: '75%',
        option_e: '70%',
        correct_answer: 'D',
        rationale: 'USMCA generally requires 75% RVC under the transaction value method for most goods to qualify for preferential tariff treatment.',
        reference_cue: 'USMCA Rules of Origin',
        difficulty: 3,
        domain_index: 3
    },
    {
        stem: 'A USMCA certificate of origin must be retained for:',
        option_a: '3 years',
        option_b: '5 years',
        option_c: '7 years',
        option_d: '10 years',
        option_e: '1 year',
        correct_answer: 'B',
        rationale: 'USMCA requires that certificates of origin be maintained for a minimum of 5 years.',
        reference_cue: 'USMCA Article 5.8',
        difficulty: 2,
        domain_index: 3
    },
    {
        stem: 'The Generalized System of Preferences (GSP) provides:',
        option_a: 'Reduced duties for all countries',
        option_b: 'Duty-free treatment for eligible products from designated beneficiary developing countries',
        option_c: 'Quota-free treatment for textiles',
        option_d: 'Expedited customs processing',
        option_e: 'Reduced inspection requirements',
        correct_answer: 'B',
        rationale: 'GSP provides duty-free treatment for specific products imported from designated beneficiary developing countries.',
        reference_cue: '19 USC 2461',
        difficulty: 1,
        domain_index: 3
    },
    {
        stem: 'Under the substantial transformation test, country of origin is the country where:',
        option_a: 'The goods were last assembled',
        option_b: 'The goods undergo a substantial transformation into a new and different article of commerce',
        option_c: 'The majority of components originate',
        option_d: 'The goods are packed for export',
        option_e: 'The goods are first sold',
        correct_answer: 'B',
        rationale: 'Substantial transformation occurs when an article emerges from processing with a new name, character, or use different from the original.',
        reference_cue: '19 CFR 134.1(b)',
        difficulty: 2,
        domain_index: 3
    },
    {
        stem: 'Which program allows US-origin goods exported for repair or alteration to return with duty only on the value of repairs?',
        option_a: 'GSP',
        option_b: 'USMCA',
        option_c: 'HTSUS Chapter 98, Subchapter II',
        option_d: 'FTZ privilege',
        option_e: 'Drawback',
        correct_answer: 'C',
        rationale: 'HTSUS 9802.00.40 and 9802.00.50 allow US-origin goods returned after repair/alteration abroad to be dutied only on the value of the foreign work.',
        reference_cue: 'HTSUS 9802',
        difficulty: 3,
        domain_index: 3
    },
    {
        stem: 'The "wholly obtained or produced" criterion for origin determination applies to:',
        option_a: 'Manufactured goods only',
        option_b: 'Goods entirely grown, harvested, or extracted in a single country',
        option_c: 'Goods that contain at least 50% domestic content',
        option_d: 'Goods assembled from imported parts',
        option_e: 'Goods processed in a free trade zone',
        correct_answer: 'B',
        rationale: 'Wholly obtained/produced applies to agricultural products, minerals, and other goods produced entirely within one country without foreign inputs.',
        reference_cue: 'USMCA Article 4.3',
        difficulty: 2,
        domain_index: 3
    },
    {
        stem: 'To claim USMCA preferential treatment, the importer must:',
        option_a: 'Present a certificate of origin at the time of entry',
        option_b: 'Have knowledge that the good qualifies, based on a certification or other supporting documentation',
        option_c: 'Obtain pre-approval from CBP',
        option_d: 'File a separate application with the Commerce Department',
        option_e: 'Have the foreign government certify the goods',
        correct_answer: 'B',
        rationale: 'Under USMCA, the importer must have a certification of origin (by importer, exporter, or producer) or reasonable knowledge that goods qualify.',
        reference_cue: 'USMCA Article 5.2',
        difficulty: 3,
        domain_index: 3
    },
    {
        stem: 'The de minimis rule under USMCA allows non-originating materials to be disregarded if their value does not exceed:',
        option_a: '5% of the transaction value',
        option_b: '7% of the transaction value',
        option_c: '10% of the transaction value',
        option_d: '15% of the transaction value',
        option_e: '20% of the transaction value',
        correct_answer: 'C',
        rationale: 'The USMCA de minimis rule allows up to 10% non-originating content (by value) to be disregarded for most goods.',
        reference_cue: 'USMCA Article 4.12',
        difficulty: 3,
        domain_index: 3
    },
    {
        stem: 'Duty drawback allows the refund of duties paid on imported merchandise that is:',
        option_a: 'Stored indefinitely in a bonded warehouse',
        option_b: 'Subsequently exported or destroyed',
        option_c: 'Sold domestically at a loss',
        option_d: 'Returned to the foreign manufacturer',
        option_e: 'Used in a Foreign Trade Zone',
        correct_answer: 'B',
        rationale: 'Drawback provides for the refund of up to 99% of duties paid on imported merchandise that is subsequently exported or destroyed.',
        reference_cue: '19 USC 1313',
        difficulty: 2,
        domain_index: 3
    },
    {
        stem: 'Which is NOT a type of drawback under 19 USC 1313?',
        option_a: 'Direct identification manufacturing drawback',
        option_b: 'Substitution manufacturing drawback',
        option_c: 'Unused merchandise drawback',
        option_d: 'Rejected merchandise drawback',
        option_e: 'Warehousing drawback',
        correct_answer: 'E',
        rationale: 'The main types are: direct identification manufacturing, substitution manufacturing, unused merchandise, and rejected merchandise drawback. "Warehousing drawback" is not a statutory category.',
        reference_cue: '19 USC 1313',
        difficulty: 3,
        domain_index: 3
    },
];
