/**
 * Batch 2 of CBLE Questions
 * 60+ new questions
 */

export const batch2Questions = [
    // ============================================
    // DOMAIN 0: Entry / Entry Summary / Release
    // ============================================
    {
        stem: 'Under 19 CFR 141.68, when is the time of entry for merchandise released under an immediate delivery permit?',
        option_a: 'When the entry summary is filed',
        option_b: 'When the cargo arrives in the port',
        option_c: 'When the application for release is filed in proper form',
        option_d: 'When the bill of lading is signed',
        option_e: 'When the duty is paid',
        correct_answer: 'C',
        rationale: '19 CFR 141.68(c) states the time of entry is the time the application for release (CBP Form 3461) is filed with CBP in proper form.',
        reference_cue: '19 CFR 141.68(c)',
        difficulty: 3,
        domain_index: 0,
    },
    {
        stem: 'What is the maximum period an extension of liquidation can be granted by CBP?',
        option_a: '90 days',
        option_b: '180 days',
        option_c: 'One year',
        option_d: 'Two years',
        option_e: 'Three years',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 159.12, CBP may extend the 1-year liquidation period for an additional period not to exceed 1 year.',
        reference_cue: '19 CFR 159.12(e)',
        difficulty: 4,
        domain_index: 0,
    },
    {
        stem: 'Which of the following describes a "Live Entry"?',
        option_a: 'Entry for live animals only',
        option_b: 'Entry where taxes must be paid immediately',
        option_c: 'Entry where both entry and entry summary are filed at the same time and duties must be deposited at that time',
        option_d: 'Entry for perishable goods only',
        option_e: 'Entry where the cargo is already at the warehouse',
        correct_answer: 'C',
        rationale: 'A live entry is one where the entry summary serves as both the entry and entry summary, and duty deposit is required for release.',
        reference_cue: '19 CFR 141.0a(f)',
        difficulty: 3,
        domain_index: 0,
    },
    {
        stem: 'Estimated duties for a consumption entry must be deposited within ___ working days after release of the merchandise.',
        option_a: '5',
        option_b: '10',
        option_c: '15',
        option_d: '30',
        option_e: '45',
        correct_answer: 'B',
        rationale: '19 CFR 142.12(a) requires the entry summary to be filed and estimated duties deposited within 10 working days after release.',
        reference_cue: '19 CFR 142.12(a)',
        difficulty: 2,
        domain_index: 0,
    },
    {
        stem: 'If an importer of record fails to file an entry summary within the required time, CBP may:',
        option_a: 'Assess liquidated damages',
        option_b: 'Seize the merchandise',
        option_c: 'Revoke the importer index number',
        option_d: 'Increase the bond amount by 500%',
        option_e: 'Charge a flat $1,000 fine per day',
        correct_answer: 'A',
        rationale: 'Failure to file entry summary within the 10-day period results in a claim for liquidated damages under the bond.',
        reference_cue: '19 CFR 142.15',
        difficulty: 3,
        domain_index: 0,
    },
    {
        stem: 'Which of the following is NOT required for a valid Power of Attorney from a corporation?',
        option_a: 'Signature by a corporate officer',
        option_b: 'Corporate seal',
        option_c: 'Date of execution',
        option_d: 'Capacity of the signer',
        option_e: 'Name of the corporation',
        correct_answer: 'B',
        rationale: 'While a corporate seal is often used, 19 CFR 141.38 states it is not required for a customs POA.',
        reference_cue: '19 CFR 141.38',
        difficulty: 4,
        domain_index: 0,
    },
    {
        stem: 'A split shipment may be entered as a single entry if the split was caused by:',
        option_a: 'The importer\'s request for faster delivery',
        option_b: 'Lack of space on the carrier',
        option_c: 'Multiple shippers using one container',
        option_d: 'The goods arriving at different ports',
        option_e: 'A change in the tariff rate',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 141.57, split shipments may be treated as a single entry if the split was due to the carrier (e.g., lack of space).',
        reference_cue: '19 CFR 141.57',
        difficulty: 4,
        domain_index: 0,
    },
    {
        stem: 'Under what circumstances can a "Quota" entry be released?',
        option_a: 'Any time after arrival',
        option_b: 'Only after CBP headquarters authorizes release based on quota priority',
        option_c: 'Only if the value is under $2,500',
        option_d: 'If the broker pays double duty',
        option_e: 'After a 30-day quarantine',
        correct_answer: 'B',
        rationale: '19 CFR 132.12 requires that quota-class merchandise be held until release is authorized based on quota priority.',
        reference_cue: '19 CFR 132.12',
        difficulty: 4,
        domain_index: 0,
    },

    // ============================================
    // DOMAIN 1: Classification (HTSUS / GRIs)
    // ============================================
    {
        stem: 'GRI 2(b) addresses the classification of:',
        option_a: 'Sets of goods',
        option_b: 'Mixtures or combinations of materials or substances',
        option_c: 'Incomplete articles',
        option_d: 'Cases and containers',
        option_e: 'Functional units',
        correct_answer: 'B',
        rationale: 'GRI 2(b) states that any reference to a material or substance includes mixtures or combinations of that material.',
        reference_cue: 'GRI 2(b)',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'Under GRI 3(b), which of the following criteria MUST be met for goods to be considered "sets put up for retail sale"?',
        option_a: 'They must consist of at least 3 components',
        option_b: 'They must be in the same HTSUS chapter',
        option_c: 'They must be put up together to meet a particular need or carry out a specific activity',
        option_d: 'They must all have the same country of origin',
        option_e: 'They must be valued at over $100',
        correct_answer: 'C',
        rationale: 'GRI 3(b) requires that sets consist of at least two different articles, be put up together to meet a particular need, and be in a form suitable for sale directly to users.',
        reference_cue: 'GRI 3(b)',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'A multi-functional machine that performs functions described in two different headings is classified according to:',
        option_a: 'GRI 1',
        option_b: 'The principal function of the machine',
        option_c: 'The heading occurring last in numerical order',
        option_d: 'The function that adds the most value',
        option_e: 'GRI 4',
        correct_answer: 'B',
        rationale: 'Section XVI Note 3 states that multi-functional machines are classified as being that machine which performs the principal function.',
        reference_cue: 'Section XVI Note 3',
        difficulty: 4,
        domain_index: 1,
    },
    {
        stem: 'Chapter 98 of the HTSUS is used for:',
        option_a: 'Temporary Importations under Bond',
        option_b: 'Special classification provisions for goods returned to the US',
        option_c: 'Antidumping duties',
        option_d: 'Illegal importations',
        option_e: 'Classification of hazardous materials',
        correct_answer: 'B',
        rationale: 'Chapter 98 contains special provisions for articles exported and returned, personal effects, and other US-specific duty treatments.',
        reference_cue: 'HTSUS Chapter 98',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Which rule is used to classify goods that cannot be classified under GRI 1, 2, or 3?',
        option_a: 'GRI 4',
        option_b: 'GRI 5',
        option_c: 'GRI 6',
        option_d: 'General Note 1',
        option_e: 'General Note 3',
        correct_answer: 'A',
        rationale: 'GRI 4 states that goods which cannot be classified in accordance with rules 1-3 shall be classified under the heading appropriate to the goods to which they are most akin.',
        reference_cue: 'GRI 4',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'A "laptop computer" is generally classified in which chapter?',
        option_a: '84',
        option_b: '85',
        option_c: '90',
        option_d: '95',
        option_e: '82',
        correct_answer: 'A',
        rationale: 'Automatic data processing machines (computers) are classified in Heading 8471.',
        reference_cue: 'HTSUS Chapter 84',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Classification of parts of general use (like screws and bolts of iron or steel) is primarily governed by:',
        option_a: 'The chapter where the machine they fit into is classified',
        option_b: 'Relative Section or Chapter Notes excluding them as "parts"',
        option_c: 'GRI 3(b) essential character',
        option_d: 'The high value of the part',
        option_e: 'GRI 6',
        correct_answer: 'B',
        rationale: 'Section XV Note 2 defines "parts of general use" and many other chapters exclude them as "parts" because they are classified in their own headings (e.g., 7318).',
        reference_cue: 'Section XV Note 2',
        difficulty: 4,
        domain_index: 1,
    },
    {
        stem: 'HTSUS Chapter 39 defines "plastics" as materials which are capable of being:',
        option_a: 'Burned without smoke',
        option_b: 'Dissolved in water',
        option_c: 'Molded, cast, or extruded into shape',
        option_d: 'Recycled at least 3 times',
        option_e: 'Stretchable by 500%',
        correct_answer: 'C',
        rationale: 'Chapter 39 Note 1 defines plastics as those materials which are or have been capable, either at the moment of polymerization or at some subsequent stage, of being formed under external influence into shape.',
        reference_cue: 'Chapter 39 Note 1',
        difficulty: 3,
        domain_index: 1,
    },

    // ============================================
    // DOMAIN 2: Valuation (19 CFR 152)
    // ============================================
    {
        stem: 'The price actually paid or payable (PAPP) includes:',
        option_a: 'All payments made by the buyer to, or for the benefit of, the seller',
        option_b: 'Only the invoice price',
        option_c: 'The price plus US inland freight',
        option_d: 'The price less marketing expenses in the US',
        option_e: 'The price plus an 8% profit margin',
        correct_answer: 'A',
        rationale: 'PAPP is the total payment made, or to be made, for imported merchandise by the buyer to, or for the benefit of, the seller.',
        reference_cue: '19 CFR 152.103(a)',
        difficulty: 3,
        domain_index: 2,
    },
    {
        stem: 'When using Deductive Value, "superdeductive" value refers to:',
        option_a: 'Deducting the value of further processing in the US',
        option_b: 'Deducting the broker fee twice',
        option_c: 'Deducting the cost of production',
        option_d: 'Deducting antidumping duties',
        option_e: 'There is no such term as superdeductive value',
        correct_answer: 'A',
        rationale: 'Superdeductive value is used when goods are further processed in the US after importation but before sale.',
        reference_cue: '19 CFR 152.105(i)',
        difficulty: 5,
        domain_index: 2,
    },
    {
        stem: 'In a "related party" transaction, transaction value is acceptable ONLY if:',
        option_a: 'An independent appraiser says so',
        option_b: 'The relationship did not influence the price',
        option_c: 'The price is at least 110% of the cost of production',
        option_d: 'The broker signs a waiver',
        option_e: 'The seller is from a WTO country',
        correct_answer: 'B',
        rationale: 'Transaction value between related parties is acceptable if the relationship did not influence the price or the price closely approximates a "test value".',
        reference_cue: '19 CFR 152.103(l)',
        difficulty: 4,
        domain_index: 2,
    },
    {
        stem: 'Dutiable value must be determined using a currency exchange rate effective on the date of:',
        option_a: 'Entry summary',
        option_b: 'Exportation',
        option_c: 'Importation',
        option_d: 'Purchase',
        option_e: 'Liquidation',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 159.32, the rate of exchange to be used is the one in effect on the date of exportation.',
        reference_cue: '19 CFR 159.32',
        difficulty: 3,
        domain_index: 2,
    },
    {
        stem: 'Under transaction value, "packing costs" include:',
        option_a: 'Only the cardboard boxes',
        option_b: 'The cost of all containers and coverings of whatever nature and of packing, whether for labor or materials',
        option_c: 'The cost of returning empty containers to the seller',
        option_d: 'The cost of protective wrapping for US inland transport',
        option_e: 'The cost of the pallets only',
        correct_answer: 'B',
        rationale: 'Packing costs added to transaction value include all containers, labor, and materials used to place the merchandise in condition, packed ready for shipment to the US.',
        reference_cue: '19 CFR 152.102(e)',
        difficulty: 3,
        domain_index: 2,
    },
    {
        stem: 'If merchandise is sold at a price that includes a rebate after importation:',
        option_a: 'The rebate is deducted from transaction value',
        option_b: 'The rebate is ignored (not deducted) from transaction value',
        option_c: 'The whole transaction is disqualified from transaction value',
        option_d: 'The rebate is added to transaction value',
        option_e: 'The duty rate is increased by 5%',
        correct_answer: 'B',
        rationale: 'Under 152.103(m), any rebate of, or other decrease in, the price actually paid or payable that is made or otherwise effected after the date of importation of the merchandise into the US shall be disregarded.',
        reference_cue: '19 CFR 152.103(m)',
        difficulty: 4,
        domain_index: 2,
    },

    // ============================================
    // DOMAIN 3: Trade Programs / Origin
    // ============================================
    {
        stem: 'Which of the following describes the "De Minimis" rule under USMCA rules of origin?',
        option_a: 'Shipments under $800 are exempt from origin rules',
        option_b: 'Goods are considered originating if non-originating materials do not exceed 10% of the value (or weight for some goods)',
        option_c: 'The broker can ignore origin for 1% of the yearly imports',
        option_d: 'Packaging is always ignored for origin purposes',
        option_e: 'It is the same as the Section 321 threshold',
        correct_answer: 'B',
        rationale: 'USMCA includes a de minimis provision allowing up to 10% of the total value (or weight in some cases) of the good to consist of non-originating materials that do not undergo the required tariff shift.',
        reference_cue: 'USMCA General Note 11',
        difficulty: 4,
        domain_index: 3,
    },
    {
        stem: 'When claiming preferential treatment under GSP, what is the minimum value-added requirement in the beneficiary country?',
        option_a: '10%',
        option_b: '25%',
        option_c: '35%',
        option_d: '50%',
        option_e: '65%',
        correct_answer: 'C',
        rationale: 'For GSP, the sum of the cost or value of materials produced in the beneficiary country plus direct costs of processing must be at least 35% of the appraised value.',
        reference_cue: '19 CFR 10.176',
        difficulty: 3,
        domain_index: 3,
    },
    {
        stem: 'The "Fungible goods" rule of origin allows an importer to:',
        option_a: 'Ignore origin if the goods are low value',
        option_b: 'Track origin using inventory management methods like FIFO or LIFO',
        option_c: 'Mix goods from any country and claim USMCA',
        option_d: 'Claim origin based on the country of the shipper',
        option_e: 'None of the above',
        correct_answer: 'B',
        rationale: 'Fungible goods (those that are interchangeable) can be tracked for origin purposes using accounting methods rather than physical separation.',
        reference_cue: '19 CFR 102.12',
        difficulty: 4,
        domain_index: 3,
    },
    {
        stem: 'Under the US-Israel Free Trade Agreement, what is the required "Product of Israel" criteria?',
        option_a: 'The article must be wholly the growth, product, or manufacture of Israel',
        option_b: 'The article must be substantially transformed in Israel',
        option_c: 'The article must be sourced from a Kibbutz',
        option_d: 'Both A and B',
        option_e: 'The article must contain 50% US content',
        correct_answer: 'D',
        rationale: 'Goods must be wholly growth/product/manufacture or substantially transformed, and meet value-added requirements.',
        reference_cue: '19 CFR 10.191',
        difficulty: 3,
        domain_index: 3,
    },
    {
        stem: 'A "Manufacturing Drawback" claim provides for a refund of duties on imported materials that are:',
        option_a: 'Sold at a loss',
        option_b: 'Used in the manufacture or production of articles which are subsequently exported',
        option_c: 'Destroyed by fire in a warehouse',
        option_d: 'Returned to the seller because they were not ordered',
        option_e: 'Donated to charity',
        correct_answer: 'B',
        rationale: 'Manufacturing drawback allows a 99% refund of duties on materials used to make products that are exported within 5 years.',
        reference_cue: '19 CFR 190.2',
        difficulty: 2,
        domain_index: 3,
    },

    // ============================================
    // DOMAIN 4: Broker Duties / POA / Records / Bonds
    // ============================================
    {
        stem: 'A broker may NOT share their fees with:',
        option_a: 'Their licensed employees',
        option_b: 'Another licensed customs broker',
        option_c: 'An unlicensed person (except for certain specific business services)',
        option_d: 'A law firm representing the broker',
        option_e: 'Their corporate parents',
        correct_answer: 'C',
        rationale: '19 CFR 111.36(b) prohibits brokers from sharing fees with unlicensed persons for customs business.',
        reference_cue: '19 CFR 111.36',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'If a broker has knowledge that a client has made an error in a filing, the broker MUST:',
        option_a: 'Report the client to CBP immediately',
        option_b: 'Advise the client of the error and the consequences',
        option_c: 'Fix the error without telling the client',
        option_d: 'Terminate the representation immediately',
        option_e: 'Wait for CBP to find the error',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 111.39, a broker must advise the client of any error or omission and the consequences of not correcting it.',
        reference_cue: '19 CFR 111.39',
        difficulty: 3,
        domain_index: 4,
    },
    {
        stem: 'A District Permit allows a broker to:',
        option_a: 'Conduct customs business in a specific port district',
        option_b: 'Import goods for their own account',
        option_c: 'Open a branch office in Canada',
        option_d: 'Hire unlimited employees',
        option_e: 'Avoid the triennial report',
        correct_answer: 'A',
        rationale: 'Brokers need a district permit for each CBP district where they conduct business, unless performing "national permit" functions.',
        reference_cue: '19 CFR 111.19',
        difficulty: 3,
        domain_index: 4,
    },
    {
        stem: 'The triennial report fee for a customs broker is currently:',
        option_a: '$100',
        option_b: '$200',
        option_c: '$100 per license plus $100 per permit',
        option_d: 'Set by CBP every 3 years',
        option_e: 'The fee was eliminated in 2022',
        correct_answer: 'D',
        rationale: 'CBP sets the fee for the status report; it is currently approx $100 but adjusted periodically.',
        reference_cue: '19 CFR 111.30',
        difficulty: 2,
        domain_index: 4,
    },
    {
        stem: 'What is the required standard for a broker when validating an importer\'s Power of Attorney?',
        option_a: 'Strict Liability',
        option_b: 'Reasonable Care',
        option_c: 'Due Diligence',
        option_d: 'Absolute Verification',
        option_e: 'No verification is required',
        correct_answer: 'C',
        rationale: 'CBP regulations and guidance require brokers to exercise due diligence to verify the identity of the person signing the POA.',
        reference_cue: '19 CFR 111.29',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'Which of the following records must be original (hard copy)?',
        option_a: 'All records must be hard copy',
        option_b: 'Powers of Attorney',
        option_c: 'Electronic records are acceptable if they meet recordkeeping standards',
        option_d: 'Only Bill of Ladings',
        option_e: 'Only Commerical Invoices',
        correct_answer: 'C',
        rationale: '19 CFR 163 allows for electronic recordkeeping if the system meets requirements for retrieval and integrity.',
        reference_cue: '19 CFR 163',
        difficulty: 2,
        domain_index: 4,
    },

    // ============================================
    // DOMAIN 5: Marking / COO (19 CFR 134)
    // ============================================
    {
        stem: 'The "J-List" refers to:',
        option_a: 'Goods from Japan',
        option_b: 'Articles exempt from individual marking requirements',
        option_c: 'Jewelry classification rules',
        option_d: 'Joint ventures between brokers',
        option_e: 'Justice Department watch list',
        correct_answer: 'B',
        rationale: 'The J-List (19 CFR 134.33) is a list of articles that are exempt from individual marking because they are usually imported in containers that are marked.',
        reference_cue: '19 CFR 134.33',
        difficulty: 3,
        domain_index: 5,
    },
    {
        stem: 'A "conspicuous" marking is one that:',
        option_a: 'Can be seen from 20 feet away',
        option_b: 'Can be easily seen with normal handling of the article',
        option_c: 'Is at least 1 inch tall',
        option_d: 'Is on the top of the box only',
        option_e: 'Is printed in red ink',
        correct_answer: 'B',
        rationale: '134.11 requires marking to be conspicuous - meaning it can be found easily and read by the ultimate purchaser.',
        reference_cue: '19 CFR 134.11',
        difficulty: 2,
        domain_index: 5,
    },
    {
        stem: 'If an article is manufactured in the US but uses foreign components:',
        option_a: 'It must be marked "Made in USA"',
        option_b: 'It must be marked "Made in USA with foreign parts"',
        option_c: 'It may be subject to FTC "Made in USA" standards which differ from CBP marking rules',
        option_d: 'It is exempt from all marking',
        option_e: 'It must be marked with the country of the most expensive part',
        correct_answer: 'C',
        rationale: 'FTC regulates "Made in USA" claims. CBP rules apply to "foreign origin" marking for imported goods.',
        reference_cue: '19 CFR 134',
        difficulty: 4,
        domain_index: 5,
    },
    {
        stem: 'A "Natural Product" like an apple or an orange:',
        option_a: 'Must be individually stickered',
        option_b: 'Is exempt from marking if in a marked container',
        option_c: 'Is on the J-List',
        option_d: 'Both B and C',
        option_e: 'Is exempt under the "De Minimis" fruit rule',
        correct_answer: 'D',
        rationale: 'Natural products like fruit are on the J-List and exempt from individual marking if the container is marked.',
        reference_cue: '19 CFR 134.33',
        difficulty: 3,
        domain_index: 5,
    },

    // ============================================
    // DOMAIN 6: Protests / Liquidation
    // ============================================
    {
        stem: 'Which of the following actions is NOT protestable?',
        option_a: 'Classification of merchandise',
        option_b: 'Appraisement of merchandise',
        option_c: 'Assessment of antidumping duties',
        option_d: 'Exclusion of merchandise from entry',
        option_e: 'Administrative fine or penalty',
        correct_answer: 'E',
        rationale: 'Fines and penalties are handled through the "Petition" process (19 CFR 171/172), not the Protest process (19 CFR 174).',
        reference_cue: '19 CFR 174.11',
        difficulty: 4,
        domain_index: 6,
    },
    {
        stem: 'A "Suspension" of liquidation occurs when:',
        option_a: 'The broker is on vacation',
        option_b: 'CBP is waiting for a court decision or a scope ruling (e.g., AD/CVD)',
        option_c: 'The importer asks for more time',
        option_d: 'The computer system is down',
        option_e: 'The duty rate is over 100%',
        correct_answer: 'B',
        rationale: 'Liquidation is suspended by law or at the direction of the court/agency, often for AD/CVD investigations.',
        reference_cue: '19 CFR 159.12',
        difficulty: 4,
        domain_index: 6,
    },
    {
        stem: 'Can an importer file a protest before the entry is liquidated?',
        option_a: 'Yes, any time',
        option_b: 'No, only after liquidation',
        option_c: 'Yes, but it stays "pending" until liquidation',
        option_d: 'Only if the value is over $1 million',
        option_e: 'Only if it involves an exclusion of goods',
        correct_answer: 'E',
        rationale: 'Generally, protests are filed after liquidation. However, for exclusions, the protest can be filed within 90 days of the exclusion.',
        reference_cue: '19 CFR 174.12',
        difficulty: 5,
        domain_index: 6,
    },
    {
        stem: 'Accelerated disposition of a protest may be requested:',
        option_a: 'At any time after filing the protest',
        option_b: 'Only by the broker',
        option_c: '90 days after the filing of the protest',
        option_d: 'If the protest is over $5,000',
        option_e: 'Never, CBP works at its own pace',
        correct_answer: 'C',
        rationale: '174.22 allows the protestant to request accelerated disposition 90 days after filing. CBP then has 30 days to act.',
        reference_cue: '19 CFR 174.22',
        difficulty: 4,
        domain_index: 6,
    },

    // ============================================
    // DOMAIN 7: Other / Miscellaneous
    // ============================================
    {
        stem: 'A "Carnet" is used for:',
        option_a: 'Importing food into the US',
        option_b: 'Temporary admission of goods without duty or bond (e.g., professional equipment, samples)',
        option_c: 'Registering a boat with CBP',
        option_d: 'Paying duties in installments',
        option_e: 'Authorizing a broker to sign for a client',
        correct_answer: 'B',
        rationale: 'ATA Carnets act as a temporary passport for goods, allowing entry without duties or regular entry docs/bonds.',
        reference_cue: '19 CFR 114',
        difficulty: 3,
        domain_index: 7,
    },
    {
        stem: 'Which status within an FTZ allows goods to be treated as if they are already outside the US for duty purposes?',
        option_a: 'Privileged Foreign Status',
        option_b: 'Non-privileged Foreign Status',
        option_c: 'Domestic Status',
        option_d: 'Zone-restricted Status',
        option_e: 'Immediate Export Status',
        correct_answer: 'D',
        rationale: 'Zone-restricted status is for goods sent to the zone for the sole purpose of exportation or destruction, and they cannot return to the US commerce.',
        reference_cue: '19 CFR 146.44',
        difficulty: 4,
        domain_index: 7,
    },
    {
        stem: 'In-bond movements (CBP Form 7512) must be initiated within ___ days of arrival.',
        option_a: '5',
        option_b: '10',
        option_c: '15',
        option_d: '30',
        option_e: '45',
        correct_answer: 'D',
        rationale: 'Merchandise arriving at a port must be entered or moved in-bond within 15 days, otherwise it goes to General Order (GO). Note: 7512 rules changed in 2018/2022.',
        reference_cue: '19 CFR 18.1',
        difficulty: 4,
        domain_index: 7,
    },
    {
        stem: 'A "Notice of Action" (CBP Form 29) that results in a duty increase is considered:',
        option_a: 'A final decision',
        option_b: 'A proposed action (if using "Proposed" checkbox)',
        option_c: 'A suggestion',
        option_d: 'An invitation to a meeting',
        option_e: 'Illegal',
        correct_answer: 'B',
        rationale: 'CBP uses Form 29 to notify importers of proposed or taken actions affecting their entries.',
        reference_cue: '19 CFR 152.2',
        difficulty: 3,
        domain_index: 7,
    },
    {
        stem: 'Intellectual Property Rights (IPR) enforcement for "Counterfeit" goods results in:',
        option_a: 'Mandatory seizure',
        option_b: 'Payment of triple duty',
        option_c: 'A warning',
        option_d: 'Re-exportation mandated',
        option_e: 'All of the above',
        correct_answer: 'A',
        rationale: 'Counterfeit marks (as opposed to confusingly similar) trigger mandatory seizure and forfeiture.',
        reference_cue: '19 CFR 133.21',
        difficulty: 4,
        domain_index: 7,
    },
];
