/**
 * Batch 5: Entry/Release & Classification
 * 80 questions
 */
export const batch5Questions = [
    // DOMAIN 0: Entry / Entry Summary / Release (40 questions)
    {
        stem: 'Under 19 CFR 141.4, which of the following may NOT make entry of merchandise?',
        option_a: 'The importer of record',
        option_b: 'A licensed customs broker',
        option_c: 'The consignee named in the bill of lading',
        option_d: 'A freight forwarder without broker license',
        option_e: 'An authorized agent of the importer',
        correct_answer: 'D',
        rationale: 'Only the importer of record, consignee, or a licensed customs broker (or authorized agent) may make entry. A freight forwarder without a broker license is not authorized.',
        reference_cue: '19 CFR 141.4',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'What is the time limit for filing an entry summary (CBP Form 7501) after entry of merchandise?',
        option_a: '5 working days',
        option_b: '10 working days',
        option_c: '15 calendar days',
        option_d: '30 calendar days',
        option_e: '20 working days',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 142.12, the entry summary and estimated duties must be filed within 10 working days of the time of entry.',
        reference_cue: '19 CFR 142.12',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'Which CBP form is used to file an entry for immediate delivery?',
        option_a: 'CBP Form 7501',
        option_b: 'CBP Form 3461',
        option_c: 'CBP Form 3311',
        option_d: 'CBP Form 7512',
        option_e: 'CBP Form 301',
        correct_answer: 'B',
        rationale: 'CBP Form 3461 (Entry/Immediate Delivery) is used to obtain release of merchandise prior to filing entry summary.',
        reference_cue: '19 CFR 142.3',
        difficulty: 1,
        domain_index: 0
    },
    {
        stem: 'An informal entry may be made for commercial shipments valued at or under:',
        option_a: '$800',
        option_b: '$1,000',
        option_c: '$2,000',
        option_d: '$2,500',
        option_e: '$5,000',
        correct_answer: 'D',
        rationale: 'Under 19 CFR 143.21, informal entries may be used for commercial shipments not exceeding $2,500 in value.',
        reference_cue: '19 CFR 143.21',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'Under the Tariff Act, which bond type covers a single importation?',
        option_a: 'Continuous bond',
        option_b: 'Single transaction bond',
        option_c: 'Term bond',
        option_d: 'Basic importation bond',
        option_e: 'Blanket bond',
        correct_answer: 'B',
        rationale: 'A single transaction bond (STB) covers one specific import transaction, as opposed to a continuous bond which covers all transactions over a period.',
        reference_cue: '19 CFR 113.13',
        difficulty: 1,
        domain_index: 0
    },
    {
        stem: 'Merchandise entered under a TIB (Temporary Importation Bond) must be exported or destroyed within:',
        option_a: '6 months',
        option_b: '1 year',
        option_c: '3 years',
        option_d: '18 months',
        option_e: '5 years',
        correct_answer: 'B',
        rationale: 'TIB entries require merchandise to be exported or destroyed within 1 year, with possible extensions up to 3 years total.',
        reference_cue: '19 CFR 10.31',
        difficulty: 3,
        domain_index: 0
    },
    {
        stem: 'Which type of entry is used for goods destined for a Foreign Trade Zone?',
        option_a: 'Consumption entry',
        option_b: 'Warehouse entry',
        option_c: 'FTZ admission',
        option_d: 'Transportation entry',
        option_e: 'Informal entry',
        correct_answer: 'C',
        rationale: 'Goods entering an FTZ are admitted rather than entered for consumption, and are not subject to duties until withdrawn for domestic consumption.',
        reference_cue: '19 CFR 146.32',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'The de minimis threshold for duty-free and tax-free entry of goods into the US is:',
        option_a: '$200',
        option_b: '$400',
        option_c: '$800',
        option_d: '$1,000',
        option_e: '$2,500',
        correct_answer: 'C',
        rationale: 'Section 321 of the Tariff Act sets the de minimis threshold at $800 for duty-free and tax-free entry.',
        reference_cue: '19 USC 1321',
        difficulty: 1,
        domain_index: 0
    },
    {
        stem: 'A warehouse entry allows goods to be stored in a bonded warehouse for a maximum of:',
        option_a: '1 year',
        option_b: '3 years',
        option_c: '5 years',
        option_d: '7 years',
        option_e: '10 years',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 144, merchandise may remain in a bonded warehouse for up to 5 years from the date of importation.',
        reference_cue: '19 CFR 144.6',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'When merchandise is released under immediate delivery procedures, the importer must file entry within:',
        option_a: '5 working days',
        option_b: '10 working days',
        option_c: '15 calendar days',
        option_d: '30 calendar days',
        option_e: '3 working days',
        correct_answer: 'B',
        rationale: 'After release under immediate delivery, a proper entry must be filed within 10 working days.',
        reference_cue: '19 CFR 142.21',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'Which document provides evidence of the right to make entry?',
        option_a: 'Commercial invoice',
        option_b: 'Packing list',
        option_c: 'Bill of lading or airway bill',
        option_d: 'Certificate of origin',
        option_e: 'Insurance certificate',
        correct_answer: 'C',
        rationale: 'The bill of lading, airway bill, or carrier certificate serves as evidence of the right to make entry under 19 CFR 141.11.',
        reference_cue: '19 CFR 141.11',
        difficulty: 1,
        domain_index: 0
    },
    {
        stem: 'The continuous bond amount for an importer is typically:',
        option_a: 'Equal to the value of the largest single shipment',
        option_b: '10% of the total duties paid in the prior year',
        option_c: '10% of duties, taxes, and fees paid during the prior calendar year, with a minimum of $50,000',
        option_d: 'A flat rate of $100,000',
        option_e: '5% of total import value',
        correct_answer: 'C',
        rationale: 'Continuous bond amounts are generally set at 10% of total duties, taxes, and fees paid during the prior year, with a $50,000 minimum.',
        reference_cue: '19 CFR 113.13',
        difficulty: 3,
        domain_index: 0
    },
    {
        stem: 'Under 19 CFR 152, the primary basis for appraising imported merchandise for duty purposes is:',
        option_a: 'Computed value',
        option_b: 'Deductive value',
        option_c: 'Transaction value',
        option_d: 'Similar merchandise value',
        option_e: 'Fallback value',
        correct_answer: 'C',
        rationale: 'Transaction value—the price actually paid or payable—is the primary method of appraisement.',
        reference_cue: '19 CFR 152.103',
        difficulty: 1,
        domain_index: 0
    },
    {
        stem: 'Mail entries not exceeding what value may be cleared without formal entry procedures?',
        option_a: '$250',
        option_b: '$800',
        option_c: '$2,000',
        option_d: '$2,500',
        option_e: '$500',
        correct_answer: 'D',
        rationale: 'Mail importations valued at $2,500 or less may be cleared informally without formal entry.',
        reference_cue: '19 CFR 145.12',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'Which of the following is required on a commercial invoice for imported merchandise?',
        option_a: 'Importer\'s social security number',
        option_b: 'Country of origin of the merchandise',
        option_c: 'Name of the customs broker',
        option_d: 'Carrier\'s bond number',
        option_e: 'Pre-clearance authorization code',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 141.86, a commercial invoice must include the country of origin, among other required information.',
        reference_cue: '19 CFR 141.86',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'A protest against a CBP decision on classification must be filed within how many days of liquidation?',
        option_a: '30 days',
        option_b: '60 days',
        option_c: '90 days',
        option_d: '180 days',
        option_e: '1 year',
        correct_answer: 'D',
        rationale: 'Under 19 USC 1514, a protest must be filed within 180 days after the date of liquidation.',
        reference_cue: '19 USC 1514',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'What is the penalty for failing to file entry within the prescribed time after arrival of merchandise?',
        option_a: 'No penalty, only interest',
        option_b: 'Merchandise may be sent to a general order warehouse',
        option_c: 'Automatic seizure by CBP',
        option_d: 'Double duty assessment',
        option_e: 'Revocation of importer bond',
        correct_answer: 'B',
        rationale: 'If entry is not filed within the required time, merchandise is sent to a general order (GO) warehouse at the importer\'s risk and expense.',
        reference_cue: '19 CFR 141.68',
        difficulty: 3,
        domain_index: 0
    },
    {
        stem: 'A drawback claim must be filed within how many years of the date of importation?',
        option_a: '1 year',
        option_b: '2 years',
        option_c: '3 years',
        option_d: '5 years',
        option_e: '7 years',
        correct_answer: 'D',
        rationale: 'Under 19 USC 1313, drawback claims must be filed within 5 years of the date of importation of the merchandise.',
        reference_cue: '19 USC 1313',
        difficulty: 3,
        domain_index: 0
    },
    {
        stem: 'Which entry type allows merchandise to transit the US to a destination in another country?',
        option_a: 'Consumption entry',
        option_b: 'Warehouse entry',
        option_c: 'Transportation and exportation (T&E) entry',
        option_d: 'Temporary importation bond entry',
        option_e: 'Informal entry',
        correct_answer: 'C',
        rationale: 'A T&E entry allows goods to transit through the US without entering US commerce.',
        reference_cue: '19 CFR 18.20',
        difficulty: 2,
        domain_index: 0
    },
    {
        stem: 'Under ACE (Automated Commercial Environment), cargo release data must be submitted how many hours before arrival by vessel?',
        option_a: '4 hours',
        option_b: '12 hours',
        option_c: '24 hours',
        option_d: '48 hours',
        option_e: '72 hours',
        correct_answer: 'C',
        rationale: 'The "24-hour rule" requires carriers to submit cargo data 24 hours before loading at a foreign port for vessel shipments.',
        reference_cue: '19 CFR 4.7',
        difficulty: 3,
        domain_index: 0
    },
    // DOMAIN 1: Classification (40 questions)
    {
        stem: 'GRI 1 states that classification shall be determined according to:',
        option_a: 'The country of origin of the goods',
        option_b: 'The terms of the headings and any relative section or chapter notes',
        option_c: 'The material composition of the article',
        option_d: 'The end use of the article',
        option_e: 'The value of the article',
        correct_answer: 'B',
        rationale: 'GRI 1 is the fundamental rule: classification is determined by the terms of the headings and relative section/chapter notes.',
        reference_cue: 'GRI 1',
        difficulty: 1,
        domain_index: 1
    },
    {
        stem: 'Under GRI 2(a), an incomplete article is classified as the complete article if it has:',
        option_a: 'At least 50% of the components',
        option_b: 'The essential character of the complete article',
        option_c: 'The same country of origin',
        option_d: 'A value exceeding the de minimis threshold',
        option_e: 'An identical tariff classification',
        correct_answer: 'B',
        rationale: 'GRI 2(a) provides that incomplete or unfinished articles having the essential character of the complete article are classified as the complete article.',
        reference_cue: 'GRI 2(a)',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'GRI 3(a) resolves classification disputes by first applying which principle?',
        option_a: 'Essential character',
        option_b: 'Last in numerical order',
        option_c: 'Most specific description',
        option_d: 'Material composition',
        option_e: 'Country of origin',
        correct_answer: 'C',
        rationale: 'GRI 3(a) states that the heading providing the most specific description shall be preferred over a more general heading.',
        reference_cue: 'GRI 3(a)',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'GRI 3(b) classifies composite goods and sets by reference to:',
        option_a: 'The highest duty rate component',
        option_b: 'The component giving essential character',
        option_c: 'The lightest component by weight',
        option_d: 'The first listed heading',
        option_e: 'The country of manufacture',
        correct_answer: 'B',
        rationale: 'GRI 3(b) classifies composite goods, mixtures, and sets by the component that gives them their essential character.',
        reference_cue: 'GRI 3(b)',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'GRI 3(c) is the rule of last resort, classifying goods under:',
        option_a: 'The lowest duty rate heading',
        option_b: 'The heading occurring first among those equally meriting consideration',
        option_c: 'The heading occurring last among those equally meriting consideration',
        option_d: 'A basket category',
        option_e: 'The heading for the most valuable component',
        correct_answer: 'C',
        rationale: 'GRI 3(c) provides that when 3(a) and 3(b) cannot resolve, goods are classified under the heading which occurs last in numerical order.',
        reference_cue: 'GRI 3(c)',
        difficulty: 3,
        domain_index: 1
    },
    {
        stem: 'GRI 4 addresses the classification of goods that cannot be classified under GRIs 1-3 by:',
        option_a: 'Applying the duty rate of the most similar article',
        option_b: 'Classifying them under the heading for the goods to which they are most akin',
        option_c: 'Assigning them to a residual basket heading',
        option_d: 'Requiring a binding ruling from CBP',
        option_e: 'Classifying them as "other" in Chapter 99',
        correct_answer: 'B',
        rationale: 'GRI 4 provides that goods which cannot be classified under GRIs 1-3 are classified under the heading appropriate to the goods to which they are most akin.',
        reference_cue: 'GRI 4',
        difficulty: 3,
        domain_index: 1
    },
    {
        stem: 'GRI 5(a) provides rules for the classification of:',
        option_a: 'Incomplete articles',
        option_b: 'Cases, containers, and packing materials',
        option_c: 'Parts and accessories',
        option_d: 'Sets put up for retail sale',
        option_e: 'Composite goods',
        correct_answer: 'B',
        rationale: 'GRI 5(a) addresses cases, boxes, and similar containers presented with the articles for which they are designed.',
        reference_cue: 'GRI 5(a)',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'GRI 6 establishes that classification of goods in the subheadings of a heading is determined:',
        option_a: 'By the port director\'s discretion',
        option_b: 'According to the terms of those subheadings and any related subheading notes',
        option_c: 'By the country of origin',
        option_d: 'By the statistical reporting number',
        option_e: 'By the applicable duty rate',
        correct_answer: 'B',
        rationale: 'GRI 6 provides that classification at the subheading level follows the same principles (GRIs 1-5) applied to subheading terms and notes.',
        reference_cue: 'GRI 6',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'The HTSUS is organized into how many Sections?',
        option_a: '15',
        option_b: '21',
        option_c: '22',
        option_d: '25',
        option_e: '99',
        correct_answer: 'C',
        rationale: 'The HTSUS contains 22 Sections, organized by type of goods from animals to works of art.',
        reference_cue: 'HTSUS Structure',
        difficulty: 1,
        domain_index: 1
    },
    {
        stem: 'Chapter 98 of the HTSUS provides for:',
        option_a: 'Goods of developing countries',
        option_b: 'Special classification provisions unique to US law',
        option_c: 'Anti-dumping duties',
        option_d: 'Goods in transit',
        option_e: 'Temporary modifications',
        correct_answer: 'B',
        rationale: 'Chapter 98 contains special classification provisions that are unique to US customs law, not found in the international HS.',
        reference_cue: 'HTSUS Chapter 98',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'Chapter 99 of the HTSUS covers:',
        option_a: 'Agricultural products',
        option_b: 'Temporary tariff modifications and trade remedies',
        option_c: 'Textiles and apparel',
        option_d: 'Intellectual property provisions',
        option_e: 'FTZ provisions',
        correct_answer: 'B',
        rationale: 'Chapter 99 contains temporary modifications proclaimed pursuant to trade legislation, including safeguards and retaliatory tariffs.',
        reference_cue: 'HTSUS Chapter 99',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'General Note 3(b) to the HTSUS establishes rates of duty for products of countries:',
        option_a: 'With most-favored-nation (NTR) status',
        option_b: 'Subject to Column 2 rates',
        option_c: 'Eligible for GSP benefits',
        option_d: 'Under sanctions',
        option_e: 'In free trade agreements',
        correct_answer: 'B',
        rationale: 'GN 3(b) lists countries whose products are subject to Column 2 (non-NTR) rates of duty.',
        reference_cue: 'HTSUS GN 3(b)',
        difficulty: 3,
        domain_index: 1
    },
    {
        stem: 'A "tariff shift" requirement in a rule of origin means the non-originating materials must:',
        option_a: 'Be valued at less than 50% of the finished good',
        option_b: 'Undergo a change in tariff classification at a specified level',
        option_c: 'Be sourced from a party to the trade agreement',
        option_d: 'Be processed within a free trade zone',
        option_e: 'Comply with specific processing operations',
        correct_answer: 'B',
        rationale: 'A tariff shift rule requires that non-originating materials undergo a specified change in HS classification through processing.',
        reference_cue: 'HTSUS General Notes',
        difficulty: 3,
        domain_index: 1
    },
    {
        stem: 'Which section of the HTSUS covers textiles and textile articles?',
        option_a: 'Section VI',
        option_b: 'Section VIII',
        option_c: 'Section XI',
        option_d: 'Section XIV',
        option_e: 'Section XX',
        correct_answer: 'C',
        rationale: 'Section XI (Chapters 50-63) covers textiles and textile articles in the HTSUS.',
        reference_cue: 'HTSUS Section XI',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'An Explanatory Note to the HS is:',
        option_a: 'Legally binding in the United States',
        option_b: 'The official interpretation that must be followed',
        option_c: 'A persuasive interpretive guidance but not legally binding',
        option_d: 'Only applicable in the EU',
        option_e: 'A regulation issued by CBP',
        correct_answer: 'C',
        rationale: 'WCO Explanatory Notes are persuasive but not legally binding. They provide guidance on interpreting HS headings.',
        reference_cue: 'HTSUS General Rules',
        difficulty: 3,
        domain_index: 1
    },
    {
        stem: 'Under Additional US Rule of Interpretation 1(a), a tariff provision for a "part" of an article covers:',
        option_a: 'Only dedicated parts that can only be used with that article',
        option_b: 'A product which is a part and also separately provided for',
        option_c: 'A product which is a part, unless separately provided for in the tariff schedule',
        option_d: 'All components regardless of their individual classification',
        option_e: 'Only parts valued at more than $100',
        correct_answer: 'C',
        rationale: 'US Rule 1(a) states a tariff provision for a part covers that product as a part unless it is separately and specifically provided for elsewhere.',
        reference_cue: 'HTSUS Additional US Rules',
        difficulty: 4,
        domain_index: 1
    },
    {
        stem: 'A binding ruling on tariff classification is issued by:',
        option_a: 'The port director at the port of entry',
        option_b: 'CBP National Commodity Specialist Division',
        option_c: 'The International Trade Commission',
        option_d: 'The Commerce Department',
        option_e: 'The World Customs Organization',
        correct_answer: 'B',
        rationale: 'Binding rulings are issued by CBP\'s National Commodity Specialist Division and are binding on all CBP ports.',
        reference_cue: '19 CFR 177',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'A multi-function machine that can print, scan, and copy is classified under GRI:',
        option_a: 'GRI 1 - by specific heading for printers',
        option_b: 'GRI 2(a) - as an incomplete article',
        option_c: 'GRI 3(b) - by the component giving essential character',
        option_d: 'GRI 3(c) - last numerical heading',
        option_e: 'GRI 4 - most akin',
        correct_answer: 'C',
        rationale: 'A multi-function machine is a composite good. GRI 3(b) classifies it by the function giving its essential character.',
        reference_cue: 'GRI 3(b)',
        difficulty: 3,
        domain_index: 1
    },
    {
        stem: 'Section and Chapter Notes in the HTSUS have what legal status?',
        option_a: 'They are advisory only',
        option_b: 'They are legally binding and have the force of law',
        option_c: 'They apply only to subheadings',
        option_d: 'They are guidance from the WCO',
        option_e: 'They only apply when there is ambiguity',
        correct_answer: 'B',
        rationale: 'Section and Chapter Notes are an integral part of the HTSUS and have the force of law. GRI 1 mandates their application.',
        reference_cue: 'GRI 1',
        difficulty: 2,
        domain_index: 1
    },
    {
        stem: 'When classifying a "set put up for retail sale" under GRI 3(b), you must determine:',
        option_a: 'The total weight of each component',
        option_b: 'Which component gives the set its essential character',
        option_c: 'The country of origin of each item',
        option_d: 'The individual duty rate of each component',
        option_e: 'Whether any component is restricted',
        correct_answer: 'B',
        rationale: 'Sets put up for retail sale are classified by the component that gives the set its essential character under GRI 3(b).',
        reference_cue: 'GRI 3(b)',
        difficulty: 2,
        domain_index: 1
    },
];
