/**
 * Batch 4 of CBLE Questions
 * 40 new questions
 */

export const batch4Questions = [
    // ============================================
    // DOMAIN 0: Entry / Entry Summary / Release
    // ============================================
    {
        stem: 'What is the required bond amount for a "Single Transaction Bond" (STB)?',
        option_a: 'Not less than $100',
        option_b: 'Not less than 10% of the total duties and taxes',
        option_c: 'Not less than the total value of the merchandise plus all duties and fees',
        option_d: 'A minimum of $50,000 always',
        option_e: 'Exactly $10,000 for all entries',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 113 rules, a single transaction bond for an entry is usually mandated at an amount equal to the value of the goods plus duties, taxes, and fees (or 3x for restricted goods).',
        reference_cue: '19 CFR 113.13',
        difficulty: 4,
        domain_index: 0,
    },
    {
        stem: 'Under 19 CFR 141.86, which of the following is NOT required on a commercial invoice?',
        option_a: 'The port of entry',
        option_b: 'The time of day the goods were manufactured',
        option_c: 'A detailed description of the merchandise',
        option_d: 'The quantities and weight',
        option_e: 'The purchase price of each item',
        correct_answer: 'B',
        rationale: 'Invoice requirements include port, quantity, description, and price, but the specific time of day of manufacture is not required.',
        reference_cue: '19 CFR 141.86',
        difficulty: 2,
        domain_index: 0,
    },
    {
        stem: 'A "Temporary Importation under Bond" (TIB) is usually valid for how long?',
        option_a: '6 months with no extensions',
        option_b: '1 year from the date of importation, with extensions up to 3 years',
        option_c: '5 years',
        option_d: '90 days only',
        option_e: 'Until the goods are used up',
        correct_answer: 'B',
        rationale: 'TIBs are generally valid for 1 year and can be extended in 1-year increments for a total of 3 years.',
        reference_cue: '19 CFR 10.31',
        difficulty: 3,
        domain_index: 0,
    },

    // ============================================
    // DOMAIN 1: Classification (HTSUS / GRIs)
    // ============================================
    {
        stem: 'Heading 8433 covers harvesting or threshing machinery. Which of the following would NOT be classified under 8433?',
        option_a: 'Lawn mowers',
        option_b: 'Egg graders',
        option_c: 'Straw balers',
        option_d: 'Tractors used in agriculture',
        option_e: 'Combine harvester-threshers',
        correct_answer: 'D',
        rationale: 'Tractors are classified in Heading 8701. Heading 8433 specifically excludes tractors.',
        reference_cue: 'HTSUS 8433',
        difficulty: 4,
        domain_index: 1,
    },
    {
        stem: 'Under GRI 3(a), when two or more headings each refer to only part of the materials or substances contained in mixed or composite goods, those headings are to be regarded as:',
        option_a: 'Equally specific',
        option_b: 'Mutually exclusive',
        option_c: 'GRI 1 headings',
        option_d: 'Insufficient for classification',
        option_e: 'Void',
        correct_answer: 'A',
        rationale: 'GRI 3(a) states that if two headings refer only to part of the material, they are considered equally specific even if one is more detailed.',
        reference_cue: 'GRI 3(a)',
        difficulty: 5,
        domain_index: 1,
    },
    {
        stem: 'The term "Handicapped Person" for purposes of Chapter 98 duty-free treatment is defined as any person having a permanent or temporary physical or mental impairment that:',
        option_a: 'Requires a wheelchair',
        option_b: 'Substantially limits one or more major life activities',
        option_c: 'Prevents them from working',
        option_d: 'Was acquired after birth',
        option_e: 'Is recognized by the Social Security Administration only',
        correct_answer: 'B',
        rationale: 'Chapter 98 Subchapter XVII Note 4 provides this broad definition for "handicapped" articles duty-free treatment.',
        reference_cue: 'Chapter 98 Subchapter XVII',
        difficulty: 4,
        domain_index: 1,
    },
    {
        stem: 'HTSUS Chapter 40 covers rubber. The term "Hard Rubber" specifically refers to:',
        option_a: 'Tires for trucks',
        option_b: 'Rubber with a high sulfur content (Ebonite)',
        option_c: 'Rubber infused with steel wire',
        option_d: 'Rubber that has sat in the sun too long',
        option_e: 'Synthetic rubber only',
        correct_answer: 'B',
        rationale: 'Chapter 40 Note 9 defines hard rubber as rubber obtained by vulcanization with a high proportion of sulfur.',
        reference_cue: 'Chapter 40 Note 9',
        difficulty: 5,
        domain_index: 1,
    },

    // ============================================
    // DOMAIN 2: Valuation (19 CFR 152)
    // ============================================
    {
        stem: 'Under computed value, if the profit and general expenses of the producer are inconsistent with those usually reflected in sales of identical or similar merchandise, CBP may:',
        option_a: 'Reject the computed value method',
        option_b: 'Use the profit and general expenses usually reflected in such sales',
        option_c: 'Fine the producer for inaccuracies',
        option_d: 'Add a 25% surcharge to the valuation',
        option_e: 'Require an audit of the entire factory',
        correct_answer: 'B',
        rationale: '152.106(c) allows CBP to use industry-standard profit/expense ratios if the producer\'s numbers are non-standard for the industry/country.',
        reference_cue: '19 CFR 152.106(c)',
        difficulty: 5,
        domain_index: 2,
    },
    {
        stem: 'An "Addition to the price actually paid or payable" for royalties or license fees is only made if they are paid as a:',
        option_a: 'Lump sum before shipping',
        option_b: 'Condition of the sale of the imported merchandise for export to the United States',
        option_c: 'Percentage of US sales',
        option_d: 'Fee to the US government',
        option_e: 'Payment to the customs broker',
        correct_answer: 'B',
        rationale: 'Under 152.103(f), royalties must be a condition of the export sale to be dutiable additions.',
        reference_cue: '19 CFR 152.103(f)',
        difficulty: 4,
        domain_index: 2,
    },

    // ============================================
    // DOMAIN 3: Trade Programs / Origin
    // ============================================
    {
        stem: 'The Generalized System of Preferences (GSP) is currently:',
        option_a: 'Permanent law',
        option_b: 'Subject to periodic renewal by Congress',
        option_c: 'Part of the USMCA agreement',
        option_d: 'Only for agricultural goods',
        option_e: 'Applicable to Column 2 countries',
        correct_answer: 'B',
        rationale: 'GSP is not permanent and must be reauthorized by Congress (and frequently expires and is later renewed retroactively).',
        reference_cue: 'GSP Program Status',
        difficulty: 3,
        domain_index: 3,
    },
    {
        stem: 'Under General Note 4, which countries are generally excluded from Generalized System of Preferences (GSP) treatment?',
        option_a: 'All developed countries',
        option_b: 'CBP "Column 2" countries like North Korea and Cuba',
        option_c: 'Members of the European Union only',
        option_d: 'Any country with a trade deficit',
        option_e: 'Only countries in South America',
        correct_answer: 'B',
        rationale: 'General Note 4 excludes non-market economies and Column 2 countries from GSP.',
        reference_cue: 'HTSUS General Note 4',
        difficulty: 3,
        domain_index: 3,
    },

    // ============================================
    // DOMAIN 4: Broker Duties / POA / Records / Bonds
    // ============================================
    {
        stem: 'A broker that operates as a corporation must have at least how many licensed officers at each port of entry?',
        option_a: 'One for every 10 employees',
        option_b: 'One at each port',
        option_c: 'None, they only need one for the entire corporation',
        option_d: 'Two at each port',
        option_e: 'One for the headquarters only',
        correct_answer: 'C',
        rationale: 'The "District Permit" rule was changed; now a corporation only needs one licensed officer to qualify the national license, and they must exercise "responsible supervision and control" over all districts.',
        reference_cue: '19 CFR 111.11 / 111.19',
        difficulty: 5,
        domain_index: 4,
    },
    {
        stem: 'If a broker discovers they are missing a required triennial report for 2021, what should they do?',
        option_a: 'Pretend it was submitted',
        option_b: 'Submit it immediately with the required fee to CBP',
        option_c: 'Apply for a new license',
        option_d: 'Wait for the next triennial in 2024',
        option_e: 'Retire',
        correct_answer: 'B',
        rationale: 'Failure to file triggers suspension. Submitting with the fee (plus potential late fee) is the correct path to restoration.',
        reference_cue: '19 CFR 111.30',
        difficulty: 4,
        domain_index: 4,
    },

    // ============================================
    // DOMAIN 5: Marking / COO (19 CFR 134)
    // ============================================
    {
        stem: 'Is it required to mark the container of an article that is on the "J-List"?',
        option_a: 'No, J-List articles are completely exempt',
        option_b: 'Yes, the outermost container in which the J-List article is imported must be marked',
        option_c: 'Only if the value is over $1,000',
        option_d: 'Only if the article is made of plastic',
        option_e: 'Only if the article is an apple',
        correct_answer: 'B',
        rationale: '19 CFR 134.33 states J-List exempts the individual item, but the container MUST be marked.',
        reference_cue: '19 CFR 134.33',
        difficulty: 3,
        domain_index: 5,
    },
    {
        stem: 'A "Substantial Transformation" for labeling purposes means there is:',
        option_a: 'A 50% price increase',
        option_b: 'A shift in HTSUS chapter',
        option_c: 'A change in name, character, or use',
        option_d: 'A new brand name applied',
        option_e: 'A change in color',
        correct_answer: 'C',
        rationale: 'This is the standard definition used by CBP for determining origin.',
        reference_cue: '19 CFR 102.1 / 134.1',
        difficulty: 2,
        domain_index: 5,
    },

    // ============================================
    // DOMAIN 6: Protests / Liquidation
    // ============================================
    {
        stem: 'A protest against a decision of CBP must be filed within how many days for an exclusion of merchandise?',
        option_a: '90 days from the date of the decision',
        option_b: '180 days from liquidation',
        option_c: '30 days from arrival',
        option_d: '6 months from the date of entry',
        option_e: 'Any time before the goods are sold',
        correct_answer: 'A',
        rationale: 'Exclusions have a shorter 90-day protest window compared to the standard 180-day window.',
        reference_cue: '19 CFR 174.12(e)',
        difficulty: 5,
        domain_index: 6,
    },
    {
        stem: 'What is "Liquidation"?',
        option_a: 'The selling of an importer\'s assets',
        option_b: 'The final computation or ascertainment of duties on an entry',
        option_c: 'A refund of duty',
        option_d: 'The destruction of counterfeit goods',
        option_e: 'The departure of a vessel',
        correct_answer: 'B',
        rationale: '19 CFR 159.1 defines liquidation as the final calculation of duties.',
        reference_cue: '19 CFR 159.1',
        difficulty: 2,
        domain_index: 6,
    },

    // ============================================
    // DOMAIN 7: Other (FTZ / Drawback / AD/CVD)
    // ============================================
    {
        stem: 'A "Certificate of Delivery" (CBP Form 7552) is used in which process?',
        option_a: 'USMCA claims',
        option_b: 'Drawback claims to track the transfer of imported merchandise',
        option_c: 'Delivery of goods to the White House',
        option_d: 'Registering a boat',
        option_e: 'Filing a protest',
        correct_answer: 'B',
        rationale: 'Form 7552 is used to track the chain of custody for drawback purposes.',
        reference_cue: '19 CFR 190.10',
        difficulty: 4,
        domain_index: 7,
    },
    {
        stem: 'Which agency is responsible for determining if "Dumping" (selling at less than fair value) has occurred?',
        option_a: 'CBP',
        option_b: 'The International Trade Commission (ITC)',
        option_c: 'The Department of Commerce (DOC)',
        option_d: 'The US Trade Representative (USTR)',
        option_e: 'The Federal Trade Commission (FTC)',
        correct_answer: 'C',
        rationale: 'The DOC determines the margin of dumping; the ITC determines the injury to US industry.',
        reference_cue: '19 CFR 351',
        difficulty: 4,
        domain_index: 7,
    },

    // Mixed Domains
    {
        stem: 'Under GRI 3(c), what is the "tie-breaker" rule?',
        option_a: 'The highest duty rate applies',
        option_b: 'The heading which occurs last in numerical order among those which equally merit consideration',
        option_c: 'The first heading in the book',
        option_d: 'The heading with the most words',
        option_e: 'The heading used by the exporter',
        correct_answer: 'B',
        rationale: 'GRI 3(c) is the final rule when 3(a) and 3(b) fail.',
        reference_cue: 'GRI 3(c)',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'A "Post Summary Correction" (PSC) can be filed for an entry up until:',
        option_a: 'Arrival of the next shipment',
        option_b: 'The entry is liquidated',
        option_c: '15 days after entry',
        option_d: '1 year after entry',
        option_e: 'Only after a protest is denied',
        correct_answer: 'B',
        rationale: 'PSC is the electronic way to fix entry data before liquidation occurs.',
        reference_cue: 'CBP ACE Entry Summary Instructions',
        difficulty: 4,
        domain_index: 0,
    },
    {
        stem: 'Section 301 duties are primarily aimed at trade practices originating in which country?',
        option_a: 'Canada',
        option_b: 'Mexico',
        option_c: 'China',
        option_d: 'Germany',
        option_e: 'Brazil',
        correct_answer: 'C',
        rationale: 'The major Section 301 tariffs of 2018-2024 target Chinese origin goods.',
        reference_cue: 'HTSUS Chapter 99',
        difficulty: 3,
        domain_index: 3,
    },
    {
        stem: 'Articles of wood are primarily classified in which HTSUS chapter?',
        option_a: '44',
        option_b: '45',
        option_c: '46',
        option_d: '48',
        option_e: '94',
        correct_answer: 'A',
        rationale: 'Chapter 44 is wood and articles of wood. 45 is cork, 46 is straw, 48 is paper, 94 is furniture.',
        reference_cue: 'HTSUS Chapter 44',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'The term "Direct Costs of Processing" for GSP purposes includes:',
        option_a: 'Advertising expenses',
        option_b: 'Salesmen\'s commissions',
        option_c: 'Direct labor and factory overhead',
        option_d: 'Profit of the manufacturer',
        option_e: 'Taxes on the factory building',
        correct_answer: 'C',
        rationale: 'Direct costs of processing are literal costs of manufacture, not sales or corporate overhead.',
        reference_cue: '19 CFR 10.178',
        difficulty: 4,
        domain_index: 3,
    },
    {
        stem: 'A broker is required to exercise "Responsible Supervision and Control" over their customs business. This includes:',
        option_a: 'Training employees',
        option_b: 'Reviewing entries',
        option_c: 'Being available for consultation',
        option_d: 'All of the above',
        option_e: 'Only being in the office 40 hours a week',
        correct_answer: 'D',
        rationale: '111.1 defines responsible supervision and control as including training, review, and availability.',
        reference_cue: '19 CFR 111.1',
        difficulty: 3,
        domain_index: 4,
    },
    {
        stem: 'If a broker\'s employee is fired for dishonesty, does the broker need to notify CBP?',
        option_a: 'No, it\'s an internal matter',
        option_b: 'Yes, within 30 days',
        option_c: 'Only if the value taken was over $5,000',
        option_d: 'Only if the employee was licensed',
        option_e: 'Yes, within 24 hours',
        correct_answer: 'B',
        rationale: 'Changes in employee status regarding "customs business" and reliability must be reported.',
        reference_cue: '19 CFR 111.28',
        difficulty: 4,
        domain_index: 4,
    },
    {
        stem: 'Special invoice requirements for "Textile articles" (19 CFR 141.89) require the reporting of:',
        option_a: 'The fiber content by weight',
        option_b: 'The color name in French',
        option_c: 'The number of buttons',
        option_d: 'The designer\'s name',
        option_e: 'The type of thread used',
        correct_answer: 'A',
        rationale: 'Textile invoices must show percentage of fiber by weight for classification.',
        reference_cue: '19 CFR 141.89',
        difficulty: 3,
        domain_index: 0,
    },
    {
        stem: 'A "Carrier\'s Certificate" (CBP Form 7529) is used to:',
        option_a: 'Pay for gas',
        option_b: 'Appoint a broker as agent to make entry',
        option_c: 'Certify the ship is clean',
        option_d: 'Track the speed of the vessel',
        option_e: 'Apply for a USMCA refund',
        correct_answer: 'B',
        rationale: 'Form 7529 is one way for a carrier to document the right to make entry.',
        reference_cue: '19 CFR 141.11',
        difficulty: 3,
        domain_index: 0,
    },
    {
        stem: 'The "Final in Numerical Order" rule is GRI:',
        option_a: '1',
        option_b: '2',
        option_c: '3(a)',
        option_d: '3(b)',
        option_e: '3(c)',
        correct_answer: 'E',
        rationale: 'GRI 3(c).',
        reference_cue: 'GRI 3(c)',
        difficulty: 1,
        domain_index: 1,
    },
    {
        stem: 'Heading 9801 relates to:',
        option_a: 'Handicapped articles',
        option_b: 'American goods returned without having been advanced in value or improved in condition',
        option_c: 'Diplomatic imports',
        option_d: 'Religious articles',
        option_e: 'Illegal drugs',
        correct_answer: 'B',
        rationale: 'One of the most used 98 chapters for duty-free returns.',
        reference_cue: 'HTSUS 9801',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Which HTSUS chapter covers "Furniture; bedding, mattresses"?',
        option_a: '90',
        option_b: '94',
        option_c: '95',
        option_d: '96',
        option_e: '97',
        correct_answer: 'B',
        rationale: 'Chapter 94.',
        reference_cue: 'HTSUS Chapter 94',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'Under transaction value, "selling commissions" are:',
        option_a: 'Nondutiable',
        option_b: 'Dutiable additions to the price actually paid or payable',
        option_c: 'Reduced by 50%',
        option_d: 'Only dutiable for air shipments',
        option_e: 'Only dutiable if paid to a relative',
        correct_answer: 'B',
        rationale: 'Unlike buying commissions, selling commissions are added to TV.',
        reference_cue: '19 CFR 152.103(b)',
        difficulty: 3,
        domain_index: 2,
    },
    {
        stem: 'A broker must return any client funds (overpayments) within how many days of receipt?',
        option_a: '10 days',
        option_b: '30 days',
        option_c: '60 days',
        option_d: 'They can keep it for future use without telling the client',
        option_e: 'One year',
        correct_answer: 'B',
        rationale: '111.29 requires prompt payment (usually interpreted as 30 days) of funds due to a client.',
        reference_cue: '19 CFR 111.29',
        difficulty: 3,
        domain_index: 4,
    },
    {
        stem: 'Which form is used for "Entry/Immediate Delivery"?',
        option_a: '3461',
        option_b: '7501',
        option_c: '19',
        option_d: '29',
        option_e: '7512',
        correct_answer: 'A',
        rationale: 'Form 3461.',
        reference_cue: '19 CFR 142.3',
        difficulty: 1,
        domain_index: 0,
    },
    {
        stem: 'USMCA regional value content (RVC) using the "Net Cost" method for heavy vehicles is:',
        option_a: '45%',
        option_b: '50%',
        option_c: '60%',
        option_d: '70% after the transition period',
        option_e: '80%',
        correct_answer: 'D',
        rationale: 'USMCA raised vehicle RVC thresholds significantly.',
        reference_cue: 'USMCA Rules',
        difficulty: 5,
        domain_index: 3,
    },
    {
        stem: 'A "Drawback Entry" (CBP Form 7551) must be filed within how many years of the date of exportation?',
        option_a: '1 year',
        option_b: '3 years',
        option_c: '5 years',
        option_d: '7 years',
        option_e: 'Indefinitely',
        correct_answer: 'C',
        rationale: 'Drawback claims have a 5-year limit under Modernization Act rules.',
        reference_cue: '19 CFR 190.7',
        difficulty: 4,
        domain_index: 7,
    },
    {
        stem: 'Which HTSUS chapter covers "Carpets and other textile floor coverings"?',
        option_a: '54',
        option_b: '55',
        option_c: '57',
        option_d: '58',
        option_e: '60',
        correct_answer: 'C',
        rationale: 'Chapter 57.',
        reference_cue: 'HTSUS Chapter 57',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'A "Binding Ruling" request should be submitted to:',
        option_a: 'The Port Director',
        option_b: 'The Commissioner of CBP',
        option_c: 'CBP National Commodity Specialist Division (NCSD) or OR&R',
        option_d: 'The local broker',
        option_e: 'A lawyer only',
        correct_answer: 'C',
        rationale: 'NCSD in New York handles the bulk of classification rulings.',
        reference_cue: '19 CFR 177',
        difficulty: 3,
        domain_index: 1,
    },
    {
        stem: 'If a question cannot be resolved by GRI 1-5, GRI 6 provides for classification:',
        option_a: 'At the subheading level',
        option_b: 'By the importer\'s preference',
        option_c: 'By the lowest duty rate',
        option_d: 'At the chapter level only',
        option_e: 'By flipping a coin',
        correct_answer: 'A',
        rationale: 'GRI 6 takes us into the subheadings.',
        reference_cue: 'GRI 6',
        difficulty: 2,
        domain_index: 1,
    },
    {
        stem: 'The ACE portal is the acronym for:',
        option_a: 'All Customs Entries',
        option_b: 'Automated Commercial Environment',
        option_c: 'American Customs Enforcement',
        option_d: 'Advanced Computer Entry',
        option_e: 'Association of Customs Executives',
        correct_answer: 'B',
        rationale: 'ACE is the primary system.',
        reference_cue: 'CBP.gov',
        difficulty: 1,
        domain_index: 0,
    },
];
