/**
 * Batch 7: Broker Duties, Marking, Penalties & Protests
 * 80 questions
 */
export const batch7Questions = [
    // DOMAIN 4: Broker Duties & Powers of Attorney (30)
    {
        stem: 'A customs broker must maintain records of customs transactions for at least:',
        option_a: '3 years',
        option_b: '5 years',
        option_c: '7 years',
        option_d: '10 years',
        option_e: '1 year',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 111.23, brokers must keep records for 5 years from the date of entry.',
        reference_cue: '19 CFR 111.23',
        difficulty: 1,
        domain_index: 4
    },
    {
        stem: 'A broker must exercise what standard of care in the conduct of customs business?',
        option_a: 'Ordinary care',
        option_b: 'Strict liability',
        option_c: 'Responsible supervision and control',
        option_d: 'Best efforts',
        option_e: 'Due diligence',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 111.1, a broker must exercise responsible supervision and control over the customs business they conduct.',
        reference_cue: '19 CFR 111.1',
        difficulty: 2,
        domain_index: 4
    },
    {
        stem: 'A broker who changes their business address must notify CBP within:',
        option_a: '10 days',
        option_b: '15 days',
        option_c: '30 days',
        option_d: '60 days',
        option_e: '90 days',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 111.30, a broker must notify CBP within 30 days of a change of business address.',
        reference_cue: '19 CFR 111.30',
        difficulty: 2,
        domain_index: 4
    },
    {
        stem: 'A customs broker license is valid:',
        option_a: 'For 3 years',
        option_b: 'For 5 years, renewable',
        option_c: 'Indefinitely, subject to triennial status reports',
        option_d: 'For 10 years',
        option_e: 'Until revoked or surrendered',
        correct_answer: 'C',
        rationale: 'A broker license remains valid indefinitely but is subject to triennial status reports filed every 3 years per 19 CFR 111.30.',
        reference_cue: '19 CFR 111.30',
        difficulty: 3,
        domain_index: 4
    },
    {
        stem: 'A power of attorney (POA) authorizing a broker to act for a partnership:',
        option_a: 'Must be signed by all partners',
        option_b: 'May be signed by any one partner',
        option_c: 'Requires notarization',
        option_d: 'Must be filed with the Secretary of State',
        option_e: 'Is not valid; only corporations can issue POAs',
        correct_answer: 'B',
        rationale: 'Under 19 CFR 141.37, a power of attorney for a partnership may be executed by any one partner.',
        reference_cue: '19 CFR 141.37',
        difficulty: 3,
        domain_index: 4
    },
    {
        stem: 'The broker exam passing score is:',
        option_a: '60%',
        option_b: '70%',
        option_c: '75%',
        option_d: '80%',
        option_e: '90%',
        correct_answer: 'C',
        rationale: 'A passing score of 75% is required on the customs broker license examination.',
        reference_cue: '19 CFR 111.11',
        difficulty: 1,
        domain_index: 4
    },
    {
        stem: 'A broker may NOT:',
        option_a: 'Charge fees for customs business',
        option_b: 'Act for multiple importers',
        option_c: 'Share fees with a non-broker who is not an employee',
        option_d: 'Prepare entry documents',
        option_e: 'Employ unlicensed staff to assist',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 111.36, a broker may not share fees with a person who is not a licensed broker or their direct employee.',
        reference_cue: '19 CFR 111.36',
        difficulty: 3,
        domain_index: 4
    },
    {
        stem: 'Under 19 CFR 111.24, a broker must promptly remit funds received from a client for:',
        option_a: 'Legal defense costs',
        option_b: 'Payment of duties, taxes, and charges',
        option_c: 'Future estimated duties',
        option_d: 'Warehouse storage fees',
        option_e: 'Penalty mitigation deposits',
        correct_answer: 'B',
        rationale: 'A broker must pay over to the government duties, taxes, and charges received from a client in connection with customs transactions.',
        reference_cue: '19 CFR 111.24',
        difficulty: 2,
        domain_index: 4
    },
    {
        stem: 'The grounds for revoking a broker license include all EXCEPT:',
        option_a: 'Conviction of a felony',
        option_b: 'Failure to file triennial report',
        option_c: 'Working for a competitor firm',
        option_d: 'Filing false documents with CBP',
        option_e: 'Tax delinquency',
        correct_answer: 'C',
        rationale: 'Working for a competitor is not grounds for revocation. Felonies, false filings, delinquent taxes, and failure to file triennial are all valid grounds.',
        reference_cue: '19 CFR 111.53',
        difficulty: 3,
        domain_index: 4
    },
    {
        stem: 'A national permit allows a broker to:',
        option_a: 'Conduct customs business in only one district',
        option_b: 'Conduct customs business in any port throughout the US',
        option_c: 'Conduct customs business in two designated districts',
        option_d: 'Act as a freight forwarder',
        option_e: 'Represent the government in customs matters',
        correct_answer: 'B',
        rationale: 'A national permit allows a broker to transact customs business at any port within the customs territory of the United States.',
        reference_cue: '19 CFR 111.19',
        difficulty: 2,
        domain_index: 4
    },
    // DOMAIN 5: Marking & Country of Origin (20)
    {
        stem: 'Under 19 CFR 134.1, imported articles must be marked to indicate the:',
        option_a: 'Name of the manufacturer',
        option_b: 'Country of origin in English',
        option_c: 'Date of manufacture',
        option_d: 'Port of importation',
        option_e: 'Customs broker who cleared them',
        correct_answer: 'B',
        rationale: 'Every article of foreign origin must be marked conspicuously, legibly, and permanently to indicate the English name of the country of origin.',
        reference_cue: '19 CFR 134.11',
        difficulty: 1,
        domain_index: 5
    },
    {
        stem: 'Which of the following is EXEMPT from country of origin marking requirements?',
        option_a: 'Clothing',
        option_b: 'Electronics',
        option_c: 'Articles for the personal use of the importer that are not for sale',
        option_d: 'Food products',
        option_e: 'Automotive parts',
        correct_answer: 'C',
        rationale: 'Under 19 CFR 134.32, articles imported for personal use and not intended for sale are exempt from marking requirements.',
        reference_cue: '19 CFR 134.32',
        difficulty: 2,
        domain_index: 5
    },
    {
        stem: 'The marking must be:',
        option_a: 'On the packaging only',
        option_b: 'On the article itself, unless an exception applies',
        option_c: 'Only on the shipping container',
        option_d: 'On the commercial invoice',
        option_e: 'In any language',
        correct_answer: 'B',
        rationale: 'Marking must be on the article itself. If the article cannot be marked, the outermost container may be marked instead under specific exceptions.',
        reference_cue: '19 CFR 134.11',
        difficulty: 2,
        domain_index: 5
    },
    {
        stem: 'The penalty for failure to mark imported goods with country of origin is:',
        option_a: 'A flat fine of $1,000',
        option_b: 'An additional duty of 10% ad valorem',
        option_c: 'Seizure of the goods',
        option_d: 'Revocation of importer bond',
        option_e: 'Denial of entry',
        correct_answer: 'B',
        rationale: 'Articles not properly marked are subject to an additional duty of 10% ad valorem under 19 USC 1304(f).',
        reference_cue: '19 USC 1304(f)',
        difficulty: 2,
        domain_index: 5
    },
    {
        stem: 'Articles that are substantially transformed in the US after importation:',
        option_a: 'Must retain the foreign country of origin marking',
        option_b: 'Are exempt from further marking requirements',
        option_c: 'Must be marked "Made in USA"',
        option_d: 'Must be marked with both countries',
        option_e: 'Are subject to double duties',
        correct_answer: 'B',
        rationale: 'If an article is substantially transformed in the US, it is excepted from marking requirements because the US becomes the country of origin.',
        reference_cue: '19 CFR 134.35(a)',
        difficulty: 3,
        domain_index: 5
    },
    {
        stem: 'The marking must be in a location that is:',
        option_a: 'Only visible upon opening',
        option_b: 'Conspicuous and in a location where the ultimate purchaser will see it',
        option_c: 'Hidden to prevent consumer confusion',
        option_d: 'Only on the bottom of the article',
        option_e: 'Inside the article',
        correct_answer: 'B',
        rationale: 'Marking must be conspicuous, legible, and permanent, placed where the ultimate purchaser in the US will see it during the normal course of handling.',
        reference_cue: '19 CFR 134.11',
        difficulty: 1,
        domain_index: 5
    },
    {
        stem: 'For USMCA marking purposes, the country of origin is determined by:',
        option_a: 'Where the goods were last sold',
        option_b: 'USMCA marking rules based on tariff shift or regional value content',
        option_c: 'Where the majority of materials originated',
        option_d: 'The country of shipment',
        option_e: 'The ultimate destination country',
        correct_answer: 'B',
        rationale: 'USMCA has specific marking rules that determine origin based on tariff shift rules or regional value content thresholds.',
        reference_cue: 'USMCA Annex 4-B',
        difficulty: 3,
        domain_index: 5
    },
    // DOMAIN 6: Penalties & Protests (15)
    {
        stem: 'A protest against a CBP decision must be filed on:',
        option_a: 'CBP Form 301',
        option_b: 'CBP Form 19',
        option_c: 'CBP Form 7501',
        option_d: 'CBP Form 3461',
        option_e: 'CBP Form 28',
        correct_answer: 'B',
        rationale: 'CBP Form 19 is the official form for filing a protest against a CBP decision.',
        reference_cue: '19 CFR 174.12',
        difficulty: 2,
        domain_index: 6
    },
    {
        stem: 'Under 19 USC 1592, a negligent violation involving fraud, gross negligence, or negligence in entering goods can result in penalties up to:',
        option_a: 'The domestic value of the merchandise for fraud',
        option_b: 'Double the lawful duties for negligence',
        option_c: 'A fixed fine of $10,000',
        option_d: '50% of the dutiable value for negligence',
        option_e: 'Imprisonment only',
        correct_answer: 'A',
        rationale: 'The maximum penalty for fraud is the domestic value of the merchandise. For gross negligence, it is 4x the lawful duties. For negligence, it is 2x the lawful duties.',
        reference_cue: '19 USC 1592',
        difficulty: 3,
        domain_index: 6
    },
    {
        stem: 'Prior disclosure of a violation under 19 USC 1592 may reduce the penalty to:',
        option_a: 'Zero',
        option_b: 'Interest on the lost revenue for negligence cases',
        option_c: 'Half of the maximum penalty',
        option_d: '25% of the maximum penalty',
        option_e: '10% of the dutiable value',
        correct_answer: 'B',
        rationale: 'A valid prior disclosure typically reduces the penalty to interest on the lost duties for negligence. Fraud cases may receive higher reduction but not elimination.',
        reference_cue: '19 CFR 162.74',
        difficulty: 4,
        domain_index: 6
    },
    {
        stem: 'A protest must be filed within how many days after the date of liquidation?',
        option_a: '30 days',
        option_b: '60 days',
        option_c: '90 days',
        option_d: '180 days',
        option_e: '365 days',
        correct_answer: 'D',
        rationale: 'Under 19 USC 1514, a protest must be filed within 180 days after the date of liquidation or other protestable decision.',
        reference_cue: '19 USC 1514',
        difficulty: 2,
        domain_index: 6
    },
    {
        stem: 'If a protest is denied, the importer may seek judicial review by filing suit in the:',
        option_a: 'US District Court',
        option_b: 'US Court of International Trade',
        option_c: 'US Tax Court',
        option_d: 'International Trade Commission',
        option_e: 'Federal Claims Court',
        correct_answer: 'B',
        rationale: 'After a denied protest, the importer may file suit in the US Court of International Trade within 180 days of denial.',
        reference_cue: '28 USC 1581',
        difficulty: 2,
        domain_index: 6
    },
    {
        stem: 'Liquidation of an entry typically occurs within:',
        option_a: '30 days of entry',
        option_b: '90 days of entry',
        option_c: '314 days of entry (approximately)',
        option_d: '1 year of entry',
        option_e: '5 years of entry',
        correct_answer: 'C',
        rationale: 'CBP generally liquidates entries within 314 days. If not liquidated within 1 year, entries are deemed liquidated as entered.',
        reference_cue: '19 USC 1504',
        difficulty: 3,
        domain_index: 6
    },
    // DOMAIN 7: Bonded Warehouse / FTZ / Other (15)
    {
        stem: 'Merchandise in a Foreign Trade Zone is considered to be:',
        option_a: 'In the customs territory of the US',
        option_b: 'Outside the customs territory of the US for duty purposes',
        option_c: 'Exempt from all US laws',
        option_d: 'Under the jurisdiction of the Commerce Department',
        option_e: 'Formally entered for consumption',
        correct_answer: 'B',
        rationale: 'FTZ merchandise is considered outside the customs territory for duty assessment purposes, although it is physically within the US.',
        reference_cue: '19 CFR 146.1',
        difficulty: 2,
        domain_index: 7
    },
    {
        stem: 'In a bonded warehouse, merchandise may undergo which activity?',
        option_a: 'Full manufacturing into a new product',
        option_b: 'Repacking, sorting, and cleaning',
        option_c: 'Retail sale to consumers',
        option_d: 'Destruction without CBP supervision',
        option_e: 'Commingling with domestic goods freely',
        correct_answer: 'B',
        rationale: 'Bonded warehouses permit limited manipulation such as repacking, sorting, cleaning, and other handling, but not manufacturing.',
        reference_cue: '19 CFR 144.34',
        difficulty: 2,
        domain_index: 7
    },
    {
        stem: 'The FTZ Board is composed of representatives from:',
        option_a: 'CBP and the IRS',
        option_b: 'The Department of Commerce and the Department of the Treasury',
        option_c: 'The State Department and CBP',
        option_d: 'Congress and the White House',
        option_e: 'CBP and the International Trade Commission',
        correct_answer: 'B',
        rationale: 'The FTZ Board consists of the Secretary of Commerce (chair) and the Secretary of the Treasury.',
        reference_cue: '19 USC 81a',
        difficulty: 3,
        domain_index: 7
    },
    {
        stem: 'Anti-dumping duties are assessed when foreign merchandise is sold in the US at:',
        option_a: 'Higher than fair market value',
        option_b: 'Less than fair value (LTFV)',
        option_c: 'The same price as domestic goods',
        option_d: 'A price set by the Commerce Department',
        option_e: 'Cost plus a reasonable profit',
        correct_answer: 'B',
        rationale: 'AD duties are assessed when the Commerce Department determines that merchandise is being sold at less than fair value, causing material injury.',
        reference_cue: '19 USC 1673',
        difficulty: 2,
        domain_index: 7
    },
    {
        stem: 'Countervailing duties compensate for:',
        option_a: 'Currency manipulation',
        option_b: 'Foreign government subsidies to manufacturers/exporters',
        option_c: 'Low labor costs abroad',
        option_d: 'Environmental regulation differences',
        option_e: 'Dumping below fair value',
        correct_answer: 'B',
        rationale: 'CVDs are imposed to offset specific subsidies provided by foreign governments to their manufacturers or exporters.',
        reference_cue: '19 USC 1671',
        difficulty: 2,
        domain_index: 7
    },
    {
        stem: 'An Importer Security Filing (ISF or "10+2") must be filed at least how many hours before vessel loading at the foreign port?',
        option_a: '12 hours',
        option_b: '24 hours',
        option_c: '48 hours',
        option_d: '72 hours',
        option_e: '96 hours',
        correct_answer: 'B',
        rationale: 'The ISF must be filed at least 24 hours before cargo is laden aboard the vessel at the foreign port.',
        reference_cue: '19 CFR 149.2',
        difficulty: 2,
        domain_index: 7
    },
];
